import {timingState,recordTimedRound,estimatePractice,timeText} from './estimate.js?v=9';
import {MidiKeys,MidiConnection,midiTargets,matchesTarget,RhythmCheck,timingWindow} from './midi.js?v=5';
import {makeCues,cueState,stepBeat,alteredNoteHeads} from './follower.js?v=10';
import {PianoSound, scheduleFrom, encodeWav} from './piano.js?v=5';
import {score as builtinScore} from './score-data.js';
import {freshState,rememberStage,switchStage,rateRound,chooseLesson,makeSections} from './practice.js?v=8';
import {parseMusicXML,readMusicXMLFile,importedExcerpt} from './import-score.js?v=12';
import {BUILTIN,progressKey,scoreId,listScores,storeScore,deleteScore} from './library.js?v=11';
let score=builtinScore, activeId=BUILTIN, library=[], beatsPerMeasure=4, pulse=1, pulsesPerMeasure=4;
import {noteName,eventsFor,detectPitch,acceptPitch,validateProgress} from './engine.js?v=5';
const $=id=>document.getElementById(id);
const builtinSections=[
 {name:'Opening pattern',start:1,end:2,goal:'Give the left-hand bass its full length. The right hand begins on the “and” of beat 1.',hint:'LH: E2 (2), then E2 (2) → B1 (5). RH: E3 with thumb; G3 + B3 with 3 + 5. For B minor: B2, then D3 + F♯3.'},
 {name:'Repeat & sustain',start:3,end:4,goal:'Keep the bass quiet and sustained while the same right-hand pattern moves above it.',hint:'LH: E2 with finger 2 in both bars. RH: eighth rest, E3, G3+B3, E3, G3+B3 quarter, E3 quarter.'},
 {name:'A minor to C and D',start:5,end:6,goal:'Respect the shared rest on beat 4 of measure 5. Prepare the low C before measure 6.',hint:'LH: A2 (1), rest on beat 4; C2 (5) → D2 (4). RH: A3, C4+E4. Next bar: G3, C4+E4, then F♯3, A3+D4.'},
 {name:'Walk down to E',start:7,end:8,goal:'Move the left hand A–G–E without rushing the chord changes.',hint:'LH: A2 (1) → G2 (2) → E2 (3). RH: A3 / C4+E4, then G3 / B3+E4; return to the E3 / G3+B3 pattern.'},
 {name:'The changing bass',start:9,end:10,goal:'Hear the difference between the held A and the E–D–C descent. RH block chords start with the bass in measure 10.',hint:'LH: A2 (1), then E2 (3), D2 (4), C2 (5). RH measure 10: E3+G3+B3, then D3+G3+B3; eighth rest, C3, E3+G3.'},
 {name:'A clean ending',start:11,end:12,goal:'Prepare the low E without an extra attack afterward. Let the final sound finish.',hint:'LH: E2 (2) → B1 (5), then E2 (2) → E1 (5). RH uses E minor and B minor in bar 11; bar 12 ends with a half rest. Shift the hand for E1; do not stretch.'},
 {name:'Join the first two phrases',start:4,end:6,goal:'Practise the E-minor-to-A-minor shift, then the rest and low C entry.',hint:'Start at bar 4, not the beginning. Keep counting through bar 5’s last beat. Prepare C2 with the pinky.'},
 {name:'Join the last two phrases',start:8,end:10,goal:'Move from sustained E to A, then place the E–D–C bass on the correct beats.',hint:'LH: bar 8 E2 (3), bar 9 A2 (1), bar 10 E2 (3) → D2 (4) → C2 (5). RH bar 10 changes to block chords.'},
 {name:'Full performance',start:1,end:12,goal:'Play both accompaniment hands through without stopping. Add the printed shaping and ritardando yourself.',hint:'Start quietly, count the rests, and keep going through a small slip. Mark one passage to revisit afterward rather than restarting.'}
];
builtinSections.push({name:'Your measure range',start:1,end:2,goal:'Work on exactly the transition you need. Keep the score visible and the pulse steady.',hint:'Look at the starting bass note and prepare the right-hand chord before counting in.'});
let sections=builtinSections, storageKey=progressKey(activeId), state;
function loadState(){let stored={};try{stored=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{}state=freshState(stored,sections,score.measures);state.practiceTiming=timingState(stored.practiceTiming);}
loadState();
let midiPractice=null,midiRhythm=null;
let cues=[],cueNodes=new Map(),followLine=null;
let piano,transport=null,positionBeat=0;
let context,playTimer=null,playGeneration=0,playing=false,micStream=null,micSource=null,micGeneration=0,micTimer=null;
function save(){rememberStage(state);try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveStatus').textContent='Saved on this device';}catch{$('saveStatus').textContent='Private browsing: progress may not save';}}
const section=()=>sections[state.section];
function handLabel(){return state.hand==='left'?'Left hand':state.hand==='right'?'Right hand':'Both piano hands';}
function rawMeasures(id){return score.abc.split('\n').filter(l=>l.startsWith('[V:'+id+']')).flatMap(l=>l.replace(/^\[V:[^\]]+\]\s*/,'').replace(/\|\]/g,'|').split('|').filter(x=>x.trim()));}
function largeScore(){return state.scoreSize==='large'||window.matchMedia('(max-width:600px)').matches;}
function excerpt(){if(score.imported)return importedExcerpt(score,state.hand,section().start,section().end,largeScore());const ids=state.hand==='left'?['LH']:state.hand==='right'?['RH']:['RH','LH'];let h='X:1\nT:Measures '+section().start+'–'+section().end+' · '+handLabel()+'\nM:4/4\nL:1/8\n%%score '+(ids.length===2?'{ RH LH }':ids[0])+'\n%%barsperstaff '+(largeScore()?1:2)+'\n%%staffwidth '+(largeScore()?300:540)+'\n%%titlefont Georgia 16\n%%stretchlast 1\n';for(const id of ids)h+='V:'+id+' clef=bass name="'+id+'"\n';h+='K:Em\n';for(const id of ids){let bars=rawMeasures(id).slice(section().start-1,section().end).map(x=>x.replace(/!>[()]!/g,'').replace(/[()]/g,''));h+='[V:'+id+'] '+bars.join(' | ')+' |]\n';}return h;}
function fingers(e){if(score.imported)return e.fingers.filter(Boolean).join(' + ');if(e.voice==='left')return e.fingers.join(' + ');const n=e.notes.join(',');const single={52:'1',47:'1',57:'1',55:'1',54:'1',48:'1'};const chords={'55,59':'3 + 5','50,54':'3 + 5','60,64':'3 + 5','57,62':'2 + 5','59,64':'3 + 5','52,55,59':'1 + 3 + 5','50,55,59':'1 + 3 + 5','52,55':'3 + 5'};return e.notes.length===1?single[n]||'':chords[n]||'';}
function render(){
 renderEstimate();
 stopAudio();stopMic();const custom=sections.length-1;sections[custom].start=state.customStart||1;sections[custom].end=state.customEnd||Math.min(2,score.measures);if(state.phase==='perform')state.section=sections.length-2;save();$('section').disabled=state.phase==='perform';$('applyRange').disabled=state.phase==='perform';$('section').options[custom].textContent='mm. '+sections[custom].start+'-'+sections[custom].end+' · Your measure range';$('section').value=state.section;$('hand').value=state.hand;$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';for(const name of ['volume','leftVolume','rightVolume']){$(name).value=state[name]??75;$(name+'Label').textContent=$(name).value+'%';}$('countBars').value=state.countBars??1;$('scoreSize').value=state.scoreSize||'standard';$('rangeStart').value=section().start;$('rangeEnd').value=section().end;$('seek').max=(section().end-section().start+1)*beatsPerMeasure;updatePosition(0);
 document.querySelectorAll('[data-phase]').forEach(b=>{b.classList.toggle('selected',b.dataset.phase===state.phase);b.setAttribute('aria-pressed',String(b.dataset.phase===state.phase));});
 $('roundLabel').textContent='ROUND '+(state.completed+(state.rated?0:1))+' · MEASURES '+section().start+'–'+section().end;
 $('lessonTitle').textContent=section().name+' · '+handLabel();$('lessonGoal').textContent=section().goal;
 $('recallPrompt').textContent=state.phase==='learn'?'With the score open: find the first note, its finger, and the first rest.':'With the score open: prepare this section’s first hand position, then start here.';$('hint').textContent=section().hint;$('hint').hidden=true;$('showHint').hidden=false;
 $('scoreWrap').hidden=false;for(const name of ['showCueGuide','autoFollow'])$(name).checked=state[name]??true;$('highlightMode').value=state.highlightMode||'notes';$('cueGuide').hidden=!$('showCueGuide').checked;
 document.body.classList.toggle('short-excerpt',section().end-section().start<2);
 try{ABCJS.renderAbc('notation',document.body.classList.contains('focus-mode')?excerpt().replace(/^T:.*\n/m,''):excerpt(),{responsive:'resize',staffwidth:largeScore()?300:540,add_classes:true,paddingright:10,paddingleft:10});bindCues();}catch(error){$('notation').textContent='Notation could not render. Use the PDF download below.';console.error(error);}
 $('noteGuide').replaceChildren();const events=eventsFor(score,state.hand,section().start,section().end);
 for(let m=section().start;m<=section().end;m++){const row=document.createElement('div');row.className='note-row';const title=document.createElement('strong');title.textContent='Bar '+m;row.append(title);const text=document.createElement('div');for(const e of events.filter(e=>Math.floor((e.beat+1e-6)/beatsPerMeasure)+1===m)){const line=document.createElement('div');let beat=e.beat%beatsPerMeasure+1,where=Number.isInteger(beat)?'Beat '+beat:'Beat '+Number(beat.toFixed(3));line.textContent=(state.hand==='both'?(e.voice==='left'?'LH ':'RH '):'')+where+': '+(e.notes.length?e.notes.map(noteName).join(' + '):'rest')+' · '+e.duration+' beat'+(e.duration===1?'':'s')+(e.notes.length&&fingers(e)?' · fingers '+fingers(e):'');text.append(line);}row.append(text);$('noteGuide').append(row);}
 $('feedback').textContent=state.rated?'This round is logged. Choose the next round button below when you are ready.':'A clean attempt means correct notes, the written rests, steady counting, and the chosen fingering.';document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=!!state.rated);$('next').textContent=state.phase==='perform'?'Start another play-through →':'Next practice round →';renderProgress();renderPlan();
}
function renderProgress(){$('progress').replaceChildren();for(let i=0;i<Math.ceil(score.measures/2);i++){const row=document.createElement('div');row.className='progress-row';const name=document.createElement('span');name.textContent='mm. '+sections[i].start+'–'+sections[i].end;const val=document.createElement('span');val.className='dots';val.textContent=['left','right','both'].map(h=>(h==='left'?'L':h==='right'?'R':'Both')+' '+Math.min(2,state.records[i+':'+h]?.clean||0)+'/2').join(' · ');row.append(name,val);$('progress').append(row);}}
async function audioContext(){if(!context){context=new (window.AudioContext||window.webkitAudioContext)();piano=new PianoSound(context);}if(context.state==='suspended')await context.resume();piano.volume((state.volume??75)/100);return context;}
function click(start,strong){piano.click(start,strong);}
function clockText(beats){let sec=Math.max(0,Math.round(beats*60/state.tempo));return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');}
function updatePosition(beat){const total=(section().end-section().start+1)*beatsPerMeasure;positionBeat=Math.max(0,Math.min(total,beat));$('seek').value=positionBeat;$('seek').setAttribute('aria-valuetext','Measure '+(section().start+Math.min(Math.floor(positionBeat/beatsPerMeasure),section().end-section().start))+', beat '+(Math.floor(positionBeat%beatsPerMeasure)+1));$('timeLabel').textContent=clockText(positionBeat)+' / '+clockText(total);}
function selectedEvents(){let events=eventsFor(score,state.hand,section().start,section().end);if($('melody').checked)events=events.concat(eventsFor(score,'melody',section().start,section().end));return events;}
function voiceLevel(voice){return voice==='left'?(state.leftVolume??70)/100:voice==='right'?(state.rightVolume??80)/100:.65;}
function highlight(notes=[],hand='right'){document.querySelectorAll('#keyboard button').forEach(k=>{k.classList.toggle('lit',notes.includes(Number(k.dataset.note)));k.classList.toggle('left',hand==='left');});}
function bindCues(){
 cues=makeCues(eventsFor(score,state.hand,section().start,section().end),state.hand,section().start,beatsPerMeasure);cueNodes=new Map();
 for(const cue of cues){const node=$('notation').querySelector(cue.selector);if(!node)throw new Error('Score cue is missing: '+cue.selector);cueNodes.set(cue,node);node.dataset.beat=cue.beat;node.dataset.voice=cue.voice;node.style.cursor='pointer';node.style.pointerEvents='bounding-box';node.onclick=()=>seekTo(cue.beat-(section().start-1)*beatsPerMeasure);
 const altered=alteredNoteHeads(cue);for(const head of node.querySelectorAll('.abcjs-notehead')){const name=(head.getAttribute('data-name')||'').replace(/^[=^_]+/,'');const pitch=altered.find(p=>p.name===name);if(pitch){head.classList.add('altered-pitch');head.setAttribute('aria-label',pitch.label);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=pitch.label;head.append(title);}}
 }
}
function cueText(list){return list.length?list.map(e=>(e.voice==='left'?'LH: ':'RH: ')+(e.notes.length?e.notes.map(noteName).join(' + ')+(fingers(e)?' · fingers '+fingers(e):''):'rest')).join(' | '):'End of section';}
function markNotes(beat){
 const at=beat<0?{current:[],next:[]}:cueState(cues,beat),mode=$('highlightMode').value;
 const m=Math.floor(beat/beatsPerMeasure)-(section().start-1);highlight(at.current.flatMap(e=>e.notes),state.hand);
 for(const [cue,node] of cueNodes){node.classList.toggle('is-current',beat>=0&&(mode==='notes'?at.current.includes(cue):mode==='measure'&&Math.floor(cue.beat/beatsPerMeasure)-(section().start-1)===m));}
 $('cueNow').textContent=beat<0?'Press Play or step through the score.':cueText(at.current);$('cueNext').textContent=beat<0?'Your next notes and fingerings will appear here.':cueText(at.next);
 if(beat<0){followLine=null;return;}
 const nodes=at.current.map(c=>cueNodes.get(c)).filter(Boolean);if(!nodes.length||!$('autoFollow').checked)return;
 const line=nodes[0].getAttribute('class').match(/abcjs-l\d+/)?.[0];if(line===followLine)return;followLine=line;
 const rects=nodes.map(n=>n.getBoundingClientRect()),top=Math.min(...rects.map(r=>r.top)),bottom=Math.max(...rects.map(r=>r.bottom));
 const toolbar=document.querySelector('.toolbar').getBoundingClientRect(),safeTop=Math.max(90,Math.min(innerHeight*.35,toolbar.bottom+16));
 if(top<safeTop||bottom>innerHeight-60)window.scrollBy({top:top-safeTop-35,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
}
function markMeasure(m){markNotes(m<0?-1:((section().start-1)*beatsPerMeasure+positionBeat));}
function seekTo(at){const was=playing,practice=transport?.practice??false;stopAudio(false);stopMic();updatePosition(at);transport={practice,paused:true};markNotes((section().start-1)*beatsPerMeasure+positionBeat);$('pause').disabled=false;$('pause').textContent='Resume';$('playStatus').textContent='Ready at measure '+(section().start+Math.floor(positionBeat/beatsPerMeasure))+'. Press Resume to continue.';if(was)play(practice,positionBeat,true);}
function stopAudio(reset=true){stopMidiPractice();playGeneration++;playing=false;if(playTimer)clearInterval(playTimer);playTimer=null;piano?.stop();document.querySelectorAll('#beatBar span').forEach(s=>s.classList.remove('active'));highlight();markMeasure(-1);$('play').textContent='▶ Hear this part';$('pause').disabled=true;$('pause').textContent='Pause';if(reset){transport=null;updatePosition(0);}$('playStatus').textContent='Read the score as you play. Use the hint or playback whenever you need it.';}
async function play(practice=false,from=positionBeat,resuming=false){
 state.practiceTiming.running=true;renderEstimate();
 stopMic();stopAudio(false);const generation=playGeneration;const total=(section().end-section().start+1)*beatsPerMeasure;if(from>=total)from=0;
 let ctx;try{ctx=await audioContext();if(!practice){$('playStatus').textContent='Loading grand piano…';await piano.load(selectedEvents().flatMap(e=>e.notes),(done,all)=>{if(generation!==playGeneration)return;$('soundState').textContent=done===all?'Grand piano loaded':'Loading piano '+done+'/'+all;});}}catch(error){if(generation===playGeneration){$('soundState').textContent='Piano could not load';$('playStatus').textContent='Could not load the piano recordings. Check your connection and press Play to retry. The score is still available.';}return;}if(generation!==playGeneration)return;
 const seconds=60/state.tempo,offset=(section().start-1)*beatsPerMeasure,start=ctx.currentTime+.12,count=resuming?0:(state.countBars??1)*beatsPerMeasure;
 const events=selectedEvents();for(let b=0;b<count/pulse;b++)click(start+b*pulse*seconds,b%pulsesPerMeasure===0);
 if(!practice)for(const e of scheduleFrom(events,offset+from,section().end*beatsPerMeasure))for(const n of e.notes)piano.note(n,start+(count+e.at)*seconds,e.length*seconds,voiceLevel(e.voice),e.voice==='left'?-.15:e.voice==='right'?.15:0);
 if($('metronome').checked)for(let b=Math.ceil(from/pulse);b<total/pulse;b++)click(start+(count+b*pulse-from)*seconds,b%pulsesPerMeasure===0);
 transport={practice,start,count,seconds,from,total,paused:false};playing=true;$('play').textContent='Playing…';$('pause').disabled=false;$('pause').textContent='Pause';if($('autoFollow').checked&&!document.body.classList.contains('focus-mode'))$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 playTimer=setInterval(()=>{if(generation!==playGeneration)return;const elapsed=(ctx.currentTime-start)/seconds;if(elapsed<0)return;if(elapsed<count){const b=Math.floor(elapsed/pulse);document.querySelectorAll('#beatBar span').forEach((s,i)=>s.classList.toggle('active',i===b%pulsesPerMeasure));$('playStatus').textContent='Count in: '+(b%pulsesPerMeasure+1)+' / '+pulsesPerMeasure+(count>beatsPerMeasure?' · bar '+(Math.floor(b/pulsesPerMeasure)+1):'');return;}let pos=elapsed-count+from;if(pos>=total){const loop=$('loop').checked&&!midiRhythm;finishMidiRhythm();clearInterval(playTimer);playTimer=null;playing=false;transport=null;$('play').textContent='▶ Hear this part';$('pause').disabled=true;document.querySelectorAll('#beatBar span').forEach(s=>s.classList.remove('active'));highlight();markMeasure(-1);updatePosition(total);$('playStatus').textContent='Finished. Let the last piano note settle, then rate your own attempt.';if(loop)setTimeout(()=>{if(generation===playGeneration)play(practice,0);},300);return;}updatePosition(pos);markNotes(offset+pos);document.querySelectorAll('#beatBar span').forEach((s,i)=>s.classList.toggle('active',i===Math.floor(pos/pulse)%pulsesPerMeasure));$('playStatus').textContent=(practice?'Your turn · ':'Listen · ')+'measure '+(section().start+Math.floor(pos/beatsPerMeasure))+' · beat '+(Math.floor(pos%beatsPerMeasure)+1);const active=events.filter(e=>offset+pos>=e.beat&&offset+pos<e.beat+e.duration);highlight(active.flatMap(e=>e.notes),state.hand);},45);
}
function pausePlayback(){if(!transport)return;if(transport.paused){play(transport.practice,positionBeat,true);return;}const current=transport,beat=Math.max(current.from,Math.min(current.total,(context.currentTime-current.start)/current.seconds-current.count+current.from));stopAudio(false);transport={...current,paused:true};updatePosition(beat);markMeasure(Math.floor(beat/beatsPerMeasure));$('pause').disabled=false;$('pause').textContent='Resume';$('playStatus').textContent='Paused. The score stays at your place.';}
function stopMic(){micGeneration++;if(micTimer)clearInterval(micTimer);micTimer=null;if(micSource)micSource.disconnect();micSource=null;if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;$('micStart').hidden=false;$('micStart').disabled=false;$('micStop').hidden=true;$('skipNote').hidden=true;$('micLabel').textContent='Microphone off';$('micTarget').textContent='Ready';$('micMeter').style.width='0';$('micStatus').textContent='Put your phone near the piano’s speaker. Use a clean piano sound and no sustain pedal for this check.';highlight();}
async function startMic(){
 if(state.hand!=='left'){state.hand='left';render();}stopAudio();stopMic();const generation=micGeneration;
 if(!navigator.mediaDevices?.getUserMedia){$('micStatus').textContent='Microphone access is unavailable. Open the HTTPS page in Safari or Chrome, or use the guide and self-checks.';return;}
 $('micStart').disabled=true;$('micStop').hidden=false;$('micStatus').textContent='Waiting for microphone permission…';let stream;
 try{const ctx=await audioContext();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(generation!==micGeneration){stream.getTracks().forEach(t=>t.stop());return;}micStream=stream;micSource=ctx.createMediaStreamSource(stream);const analyser=ctx.createAnalyser();analyser.fftSize=8192;micSource.connect(analyser);let buffer=new Float32Array(analyser.fftSize),stride=Math.max(1,Math.floor(ctx.sampleRate/12000)),down=new Float32Array(Math.floor(buffer.length/stride));
 const notes=eventsFor(score,'left',section().start,section().end).filter(e=>e.notes.length);let index=0,stableNote=null,stableSince=0,release=false,quiet=0,verified=0,skipped=0;
 $('micStart').hidden=true;$('micStop').hidden=false;$('skipNote').hidden=false;
 if(!notes.length){stopMic();$('micStatus').textContent='No left-hand notes in this section.';return;}if(notes.some(n=>n.notes.length>1)){stopMic();$('micStatus').textContent='This passage has left-hand chords. Use MIDI or self-checks for chords.';return;}const target=()=>{let n=notes[index];$('micLabel').textContent='Note '+(index+1)+' of '+notes.length+' · pitch only';$('micTarget').textContent=noteName(n.notes[0])+(n.fingers[0]?' · finger '+n.fingers[0]:'');$('micStatus').textContent='Play and hold this single note. Release fully before the next note.';highlight(n.notes,'left');markNotes(n.beat);$('playStatus').textContent='Mic target: '+noteName(n.notes[0])+(n.fingers[0]?' · finger '+n.fingers[0]:'')+' · release fully between notes';};
 const advance=manual=>{if(manual)skipped++;else verified++;index++;stableNote=null;stableSince=0;release=true;quiet=0;if(index>=notes.length){stopMic();$('micLabel').textContent='Pitch round complete';$('micTarget').textContent=verified+' / '+notes.length+' detected';$('micStatus').textContent=(skipped?skipped+' manually skipped. ':'')+'Now play the section with its written rhythm. Pitch matches alone do not verify timing or fingers.';$('playStatus').textContent='Pitch round complete: '+verified+' / '+notes.length+' detected. Now practise the written rhythm.';markMeasure(-1);return;}target();};
 $('skipNote').onclick=()=>advance(true);target();if($('autoFollow').checked&&!document.body.classList.contains('focus-mode'))$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 micTimer=setInterval(()=>{if(generation!==micGeneration)return;analyser.getFloatTimeDomainData(buffer);for(let i=0;i<down.length;i++)down[i]=buffer[i*stride];let d=detectPitch(down,ctx.sampleRate/stride);$('micMeter').style.width=Math.min(100,d.rms*600)+'%';let now=performance.now();if(d.midi===null){stableNote=null;stableSince=0;if(!quiet)quiet=now;if(now-quiet>100)release=false;return;}quiet=0;if(release){$('micStatus').textContent='Release the key and let it become quiet before the next note.';return;}if(d.midi!==stableNote){stableNote=d.midi;stableSince=now;}const expected=notes[index].notes[0];if(acceptPitch(d,expected,now-stableSince)){advance(false);}else if(d.confidence>.85&&now-stableSince>160){$('micStatus').textContent=d.midi===expected?'Hold the note steadily…':'Heard '+noteName(d.midi)+'. Find '+noteName(expected)+(Math.abs(d.midi-expected)===12?' in the indicated octave. If this is the correct key, the mic may be hearing a harmonic.':'.');}},70);
 }catch(error){if(stream)stream.getTracks().forEach(t=>t.stop());if(generation!==micGeneration)return;stopMic();$('micStatus').textContent=error.name==='NotAllowedError'?'Microphone permission was declined. You can keep practising with playback and self-checks.':'Could not start the microphone. Check your browser and microphone, or use self-checks.';}
}
function fillSelectors(){
 $('section').replaceChildren();for(let i=0;i<sections.length;i++){const o=new Option('mm. '+sections[i].start+'–'+sections[i].end+' · '+sections[i].name,i);$('section').append(o);}
 for(const id of ['rangeStart','rangeEnd']){$(id).replaceChildren();for(let i=1;i<=score.measures;i++)$(id).append(new Option(i,i));}
 $('beatBar').replaceChildren();for(let i=0;i<pulsesPerMeasure;i++){const b=document.createElement('span');b.textContent=i+1;$('beatBar').append(b);}
 $('pieceTitle').textContent=score.title;$('measureCount').textContent=score.measures+' measures';$('brandTitle').textContent=score.title;
 $('scoreNotes').textContent=score.imported?'Imported piano score. Printed fingerings are retained where supplied. Playback counts quarter-note beats.':'Both accompaniment staves use bass clef. Middle C = C4. The top melody is a separate part.';
 $('melody').checked=false;$('melody').parentElement.hidden=!!score.imported;
 document.querySelectorAll('a[href^="Black-Is-the-Color"]').forEach(a=>a.hidden=!!score.imported);
 $('libraryWarnings').textContent=(score.warnings||[]).join(' ');$('downloadScore').hidden=!score.imported;$('removeScore').hidden=!score.imported;
}
fillSelectors();
$('section').onchange=()=>{state.section=Number($('section').value);render();};$('hand').onchange=()=>{state.hand=$('hand').value;render();};$('tempo').oninput=()=>{$('bpmLabel').textContent=$('tempo').value+' BPM';};$('tempo').onchange=()=>{const was=playing,practice=transport?.practice,at=positionBeat;stopAudio(false);state.tempo=Number($('tempo').value);updatePosition(at);save();if(was)play(practice,at,true);};
document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{switchStage(state,b.dataset.phase);render();});
$('showHint').onclick=()=>{$('hint').hidden=false;$('showHint').hidden=true;};$('play').onclick=()=>play();$('pause').onclick=pausePlayback;$('stop').onclick=()=>{stopAudio();stopMic();};$('countIn').onclick=()=>play(true);$('micStart').onclick=startMic;$('micStop').onclick=stopMic;
document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{if(!rateRound(state))return;stopAudio();stopMic();const rating=Number(b.dataset.rating);if(state.phase!=='perform')recordTimedRound(state.practiceTiming,rating);renderEstimate();const key=state.section+':'+state.hand,prev=state.records[key]||{attempts:0,clean:0};prev.attempts++;prev.clean=rating===2?prev.clean+1:0;prev.last=Date.now();prev.tempo=state.tempo;prev.rating=rating;state.records[key]=prev;document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);$('feedback').textContent=rating===0?'Slow down 5 BPM, work only the rough change once, then switch sections. Return to this one after another round.':rating===1?'Keep the same tempo. Name the stumble, rehearse that transition once, and return after a different section.':prev.clean>=2?'Two clean returns logged. Try 5 BPM faster next time, or return tomorrow with the score.':'Clean attempt logged. Switch sections now, then test this one again from the score.';if(rating===0){state.tempo=Math.max(30,state.tempo-5);$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';}save();renderProgress();renderPlan();});
$('next').onclick=()=>{if(!state.rated){$('feedback').textContent='Rate your attempt first to complete this round. Navigation never adds a round.';return;}Object.assign(state,chooseLesson(state,sections,score.measures));state.rated=false;state.practiceTiming.roundSeconds=0;state.practiceTiming.running=true;render();if(!document.body.classList.contains('focus-mode'))$('lessonTitle').scrollIntoView({behavior:'smooth',block:'start'});};
$('exportProgress').onclick=async()=>{save();try{const entries=await listScores();downloadJSON({version:2,activeId,entries,progress:Object.fromEntries([BUILTIN,...entries.map(e=>e.id)].map(id=>[id,JSON.parse(localStorage.getItem(progressKey(id))||'{}')]))},'piano-repertoire-backup.json');$('importStatus').textContent='Library and progress backup downloaded.';}catch(error){$('importStatus').textContent='Backup failed: '+error.message;}};
let whites=0;for(let n=28;n<=76;n++){const black=[1,3,6,8,10].includes(n%12),key=document.createElement('button');key.dataset.note=n;key.textContent=noteName(n);key.setAttribute('aria-label','Play '+noteName(n));if(black){key.className='black';key.style.left=(whites*30-10)+'px';}else whites++;key.onclick=async()=>{if(micStream)return;$('playStatus').textContent='Keyboard reference: '+noteName(n);try{await audioContext();const generation=playGeneration;await piano.load([n]);if(generation!==playGeneration||micStream)return;piano.note(n,context.currentTime+.01,1,.75);highlight([n]);}catch{$('playStatus').textContent='Audio unavailable.';}};$('keyboard').append(key);}$('keyboard').style.minWidth=(whites*30)+'px';

$('applyRange').onclick=()=>{const start=Number($('rangeStart').value),end=Number($('rangeEnd').value);if(start>end){$('rangeError').textContent='The first measure must come before the last measure.';return;}$('rangeError').textContent='';state.customStart=start;state.customEnd=end;state.section=sections.length-1;render();};
function setPracticeView(compact){document.body.classList.toggle('focus-mode',compact);$('focusMode').setAttribute('aria-pressed',String(compact));$('focusMode').textContent=compact?'Full view':'Compact view';try{localStorage.setItem('piano-compact-view',String(compact));}catch{}}
try{setPracticeView(localStorage.getItem('piano-compact-view')!=='false');}catch{setPracticeView(true);}
$('focusMode').onclick=()=>{setPracticeView(!document.body.classList.contains('focus-mode'));render();};
$('toggleLibrary').onclick=()=>{const open=document.body.classList.toggle('library-open');$('toggleLibrary').setAttribute('aria-expanded',String(open));$('toggleLibrary').textContent=open?'Hide library':'Show library';};
for(const name of ['volume','leftVolume','rightVolume'])$(name).oninput=()=>{state[name]=Number($(name).value);$(name+'Label').textContent=state[name]+'%';if(name==='volume')piano?.volume(state.volume/100);};
for(const name of ['volume','leftVolume','rightVolume'])$(name).onchange=()=>{save();if(name!=='volume'&&playing)play(transport.practice,positionBeat,true);};
$('countBars').onchange=()=>{state.countBars=Number($('countBars').value);save();};
$('scoreSize').onchange=()=>{state.scoreSize=$('scoreSize').value;render();};
$('seek').oninput=()=>{$('timeLabel').textContent=clockText(Number($('seek').value))+' / '+clockText((section().end-section().start+1)*beatsPerMeasure);};
$('seek').onchange=()=>seekTo(Number($('seek').value));
$('importProgress').onchange=restoreBackup;
$('downloadAudio').onclick=async()=>{const button=$('downloadAudio');button.disabled=true;stopAudio();stopMic();try{const tempo=state.tempo,start=(section().start-1)*beatsPerMeasure,end=section().end*beatsPerMeasure,events=selectedEvents(),length=end-start,levels={left:voiceLevel('left'),right:voiceLevel('right'),melody:.65},volume=(state.volume??75)/100,filename=score.title.replace(/[^a-z0-9]+/gi,'-')+'-mm-'+section().start+'-'+section().end+'-'+state.hand+'-'+tempo+'bpm.wav';const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)throw new Error('Audio export is not available in this browser.');const offline=new Offline(2,Math.ceil((length*60/tempo+.7)*44100),44100),instrument=new PianoSound(offline);instrument.volume(volume);await instrument.load(events.flatMap(e=>e.notes),(done,all)=>{$('downloadStatus').textContent='Preparing piano samples '+done+'/'+all+'…';});$('downloadStatus').textContent='Rendering your piano audio…';for(const e of scheduleFrom(events,start,end))for(const n of e.notes)instrument.note(n,.03+e.at*60/tempo,e.length*60/tempo,levels[e.voice],e.voice==='left'?-.15:e.voice==='right'?.15:0);const audio=await offline.startRendering(),blob=encodeWav(audio),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('downloadStatus').textContent='Piano WAV ready: '+filename+'. No count-in or metronome. Credit Alexander Holm if redistributing this sampled audio.';}catch(error){$('downloadStatus').textContent='Could not export the audio. Check the connection and try again. '+error.message;}finally{button.disabled=false;}};
document.addEventListener('keydown',event=>{if(event.code!=='Space'||/INPUT|SELECT|TEXTAREA|BUTTON|SUMMARY|A/.test(event.target.tagName)||event.target.isContentEditable)return;event.preventDefault();if(transport)pausePlayback();else play();});

document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();stopMic();}});window.addEventListener('pagehide',()=>{stopAudio();stopMic();});render();

$('restoreProgress').onclick=()=>$('importProgress').click();

for(const id of ['highlightMode','showCueGuide','autoFollow'])$(id).onchange=()=>{state[id]=$(id).type==='checkbox'?$(id).checked:$(id).value;save();$('cueGuide').hidden=!$('showCueGuide').checked;followLine=null;markNotes((section().start-1)*beatsPerMeasure+positionBeat);};
for(const [id,direction] of [['previousNote',-1],['nextNote',1]])$(id).onclick=()=>{const at=stepBeat(cues,(section().start-1)*beatsPerMeasure+positionBeat,direction);if(at!==undefined){stopAudio(false);seekTo(at-(section().start-1)*beatsPerMeasure);}};

const midiKeys=new MidiKeys();let midiAttacks=new Set();
function stopMidiPractice(){if(midiRhythm)$('midiResults').textContent='Timed check cancelled because playback stopped or changed. Start a new check for a complete result.';midiPractice=null;midiRhythm=null;if($('midiStop')){$('midiStop').hidden=true;$('midiStart').hidden=false;$('midiFeedback').textContent='Uses your selected section and hand(s). Checks notes and octaves, including chords. Rests and timing are self-checked.';}}
function clearMidi(){if(midiRhythm||midiPractice)stopAudio();stopMidiPractice();midiKeys.clear();midiAttacks.clear();$('midiHeard').textContent='None';document.querySelectorAll('#keyboard .midi-held').forEach(n=>n.classList.remove('midi-held'));$('midiStart').disabled=true;$('midiTimed').disabled=true;}
const midiConnection=new MidiConnection({onPorts:(ports,selected)=>{
 const select=$('midiInput');select.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=ports.length?'Select your piano':'No MIDI inputs found';select.append(placeholder);
 for(const port of ports){const o=document.createElement('option');o.value=port.id;o.textContent=port.name||port.manufacturer||'MIDI input';select.append(o);}select.value=selected||'';select.disabled=!ports.length;
 $('midiStatus').textContent=selected?'Connected. Play a key to check reception.':ports.length?'Choose your piano from MIDI input.':'No MIDI inputs found. Connect and turn on the piano; this list updates automatically.';
},onLost:()=>{clearMidi();$('midiStatus').textContent='MIDI input disconnected or changed. Select a connected input to continue.';},onMessage:data=>{
 const message=midiKeys.read(data,$('midiChannel').value);if(!message)return;const held=midiKeys.notes();$('midiHeard').textContent=held.length?held.map(noteName).join(' + '):'None';document.querySelectorAll('#keyboard button').forEach(n=>n.classList.toggle('midi-held',held.includes(Number(n.dataset.note))));
 if(midiRhythm&&message.type==='on'&&transport&&!transport.paused){const absolute=(context.currentTime-transport.start)-transport.count*transport.seconds+((section().start-1)*beatsPerMeasure+transport.from)*transport.seconds;const result=midiRhythm.hit(message.note,absolute);$('midiFeedback').textContent=result.kind==='extra'?'Unexpected '+noteName(message.note)+'. Keep the pulse going.':noteName(message.note)+': '+result.kind+(result.delta?' ('+Math.round(Math.abs(result.delta)*1000)+' ms)':'')+'. Keep going.';}
 if(!midiPractice)return;if(message.type==='on')midiAttacks.add(message.note);
 const target=midiPractice.targets[midiPractice.index];
 if(matchesTarget(target,held,midiAttacks)){
  midiPractice.index++;midiAttacks.clear();
  if(midiPractice.index===midiPractice.targets.length){const count=midiPractice.index;stopMidiPractice();markNotes(-1);$('midiFeedback').textContent='Completed '+count+' note entries. Pitches and octaves matched. Now practise the written rhythm and rests.';return;}
  showMidiTarget();
 }else{const extra=held.filter(n=>!target.notes.includes(n));$('midiFeedback').textContent=extra.length?'Release '+extra.map(noteName).join(' + ')+'. Target: '+target.notes.map(noteName).join(' + '):'Play / hold '+target.notes.map(noteName).join(' + ')+'. Replay each new or repeated note.';}
}});
for(let channel=0;channel<16;channel++){const o=document.createElement('option');o.value=channel;o.textContent=channel+1;$('midiChannel').append(o);}
$('midiConnect').onclick=async()=>{
 if(!navigator.requestMIDIAccess){$('midiStatus').textContent='This browser does not support Web MIDI. Open this HTTPS site in desktop Chrome or Edge.';return;}
 $('midiConnect').disabled=true;$('midiStatus').textContent='Waiting for MIDI permission…';
 try{await midiConnection.connect(options=>navigator.requestMIDIAccess(options));$('midiDisconnect').hidden=false;$('midiConnect').hidden=true;}catch(error){$('midiStatus').textContent=error.name==='NotAllowedError'?'MIDI permission was blocked. Allow MIDI for this site, or open it directly in desktop Chrome or Edge.':'Could not open MIDI: '+error.message;}finally{$('midiConnect').disabled=false;}
};
$('midiInput').onchange=async()=>{try{await midiConnection.select($('midiInput').value);$('midiStart').disabled=!midiConnection.input;$('midiTimed').disabled=!midiConnection.input;$('midiStatus').textContent=midiConnection.input?'Connected to '+midiConnection.input.name+'. Play a key.':'Select a MIDI input.';}catch(error){clearMidi();$('midiStatus').textContent='Could not open that input. Close other MIDI apps and try again.';}};
$('midiChannel').onchange=()=>{clearMidi();$('midiStart').disabled=!midiConnection.input;$('midiTimed').disabled=!midiConnection.input;$('midiStatus').textContent='Channel changed. Release the keys before playing again.';};
$('midiDisconnect').onclick=()=>{midiConnection.disconnect();$('midiInput').replaceChildren();$('midiInput').disabled=true;$('midiDisconnect').hidden=true;$('midiConnect').hidden=false;$('midiStatus').textContent='MIDI disconnected.';};
function showMidiTarget(){const target=midiPractice.targets[midiPractice.index];updatePosition(target.beat-(section().start-1)*beatsPerMeasure);markNotes(target.beat);$('midiFeedback').textContent='Entry '+(midiPractice.index+1)+' of '+midiPractice.targets.length+': play / hold '+target.notes.map(noteName).join(' + ')+'.';$('playStatus').textContent='MIDI practice: waiting at measure '+(Math.floor(target.beat/beatsPerMeasure)+1)+'.';}
$('midiStart').onclick=()=>{if(!midiConnection.input)return;stopAudio();stopMic();midiKeys.clear();midiAttacks.clear();const targets=midiTargets(eventsFor(score,state.hand,section().start,section().end));if(!targets.length)return;midiPractice={targets,index:0};$('midiStart').hidden=true;$('midiStop').hidden=false;showMidiTarget();};
$('midiStop').onclick=()=>{stopMidiPractice();markNotes(-1);$('playStatus').textContent='MIDI practice stopped.';};
window.addEventListener('pagehide',()=>midiConnection.disconnect());

function finishMidiRhythm(){if(!midiRhythm)return;const r=midiRhythm.summary();midiRhythm=null;$('midiResults').textContent='Completed: '+r.onTime+' / '+r.expected+' on time; '+r.early+' early, '+r.late+' late, '+r.missed+' missed, '+r.wrong+' wrong-pitch, '+r.extra+' extra attacks. Checks note starts and pitches, not hold lengths, pedal, or fingering.';$('midiStop').hidden=true;$('midiStart').hidden=false;}
$('midiTimed').onclick=async()=>{if(!midiConnection.input)return;const input=midiConnection.input;stopAudio();stopMic();midiKeys.clear();midiAttacks.clear();$('midiResults').textContent='';state.countBars=Math.max(1,state.countBars??1);$('countBars').value=state.countBars;await play(true,0);if(!playing||midiConnection.input!==input)return;midiRhythm=new RhythmCheck(eventsFor(score,state.hand,section().start,section().end),state.tempo,$('midiStrictness').value);$('midiStop').hidden=false;$('midiFeedback').textContent='Count in, then follow the score. Timing window: ±'+Math.round(midiRhythm.window*1000)+' ms. Keep going after slips.';};
$('midiStop').onclick=()=>{if(midiRhythm){finishMidiRhythm();$('midiResults').textContent='Stopped early. '+$('midiResults').textContent.replace('Completed: ','');}stopAudio();stopMidiPractice();markNotes(-1);$('playStatus').textContent='MIDI practice stopped.';};

function renderPlan(){
 renderLibraryList();
 const names={learn:'Separate hands',mix:'Hands together',polish:'Polishing'},ids={learn:'targetLearn',mix:'targetMix',polish:'targetPolish'};
 $('stagePlan').replaceChildren();let total=0,remaining=0;
 for(const phase of ['learn','mix','polish']){const target=state.targets[phase],done=state.stages[phase].completed;total+=target;remaining+=Math.max(0,target-done);const item=document.createElement('div'),title=document.createElement('strong'),label=document.createElement('span'),bar=document.createElement('progress');title.textContent=names[phase];label.textContent=done+' / '+target+' rounds'+(done>target?' · '+(done-target)+' extra':'');bar.max=target;bar.value=Math.min(done,target);bar.setAttribute('aria-label',names[phase]+' completed rounds');item.append(title,label,bar);$('stagePlan').append(item);$(ids[phase]).value=target;}
 $('planTotal').textContent=total+' planned rounds · '+remaining+' remaining';
 const left=Math.max(0,(state.targets[state.phase]||0)-state.completed);
 $('stageAdvice').textContent=state.phase==='perform'?'Play through the complete piece with playback, count-in, looping, MIDI, and note navigation. Your play-throughs are saved separately.':left?left+' rounds left in this stage’s plan. Move on when you can return to the passages cleanly at a comfortable tempo. All tabs remain available.':'You have reached this stage’s target. Move to the next tab when ready, or keep going for extra rounds.';
 $('roundLabel').textContent='ROUND '+(state.completed+(state.rated?0:1))+' · MEASURES '+section().start+'–'+section().end;
}
$('saveTargets').onclick=()=>{const values=['targetLearn','targetMix','targetPolish'].map(id=>Number($(id).value));if(values.some(n=>!Number.isInteger(n)||n<1||n>10000)){$('targetStatus').textContent='Enter whole numbers between 1 and 10,000.';return;}['learn','mix','polish'].forEach((p,i)=>state.targets[p]=values[i]);save();renderPlan();$('targetStatus').textContent='Targets saved. Extra rounds are always available.';};
function downloadJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function refreshLibrary(){const select=$('scoreLibrary');select.replaceChildren(new Option(builtinScore.title,BUILTIN));for(const entry of library)select.append(new Option(entry.score.title,entry.id));select.value=activeId;renderLibraryList();}
function activateScore(id){const entry=library.find(e=>e.id===id);if(id!==BUILTIN&&!entry)return;stopAudio();stopMic();save();activeId=id;score=id===BUILTIN?builtinScore:entry.score;beatsPerMeasure=score.beatsPerMeasure||4;pulse=score.meter?Math.min(1,4/Number(score.meter.split('/')[1])):1;pulsesPerMeasure=beatsPerMeasure/pulse;sections=id===BUILTIN?builtinSections:makeSections(score.measures);storageKey=progressKey(id);loadState();fillSelectors();render();refreshLibrary();try{localStorage.setItem('piano-active-score',id);}catch{}$('midiResults').textContent='';}
$('scoreLibrary').onchange=()=>activateScore($('scoreLibrary').value);
$('addScores').onclick=()=>$('scoreFiles').click();
$('scoreFiles').onchange=async event=>{const files=[...event.target.files];if(!files.length)return;$('addScores').disabled=true;$('scoreLibrary').disabled=true;const results=[];let last=null;
 try{for(const file of files){try{const source=await readMusicXMLFile(file);let parsed,partId=null;try{parsed=parseMusicXML(source,file.name);}catch(error){if(!error.parts)throw error;partId=await choosePianoPart(error.parts,file.name);if(!partId){results.push(file.name+': import cancelled.');continue;}parsed=parseMusicXML(source,file.name,DOMParser,partId);}const id=await scoreId(partId?source+'\nPiano part: '+partId:source);if(library.some(e=>e.id===id)){results.push(file.name+': already in your library; progress kept.');last=id;continue;}const entry={id,source,filename:file.name,partId,score:parsed};await storeScore(entry);library.push(entry);last=id;results.push(file.name+': imported '+parsed.measures+' measures.');}catch(error){results.push(file.name+': '+error.message);}}if(last)activateScore(last);$('libraryStatus').textContent=results.join('\n');}finally{$('addScores').disabled=false;$('scoreLibrary').disabled=false;event.target.value='';}
};
async function restoreBackup(event){const file=event.target.files?.[0];if(!file)return;try{
 if(file.size>50000000)throw new Error('This backup exceeds 50 MB.');const data=JSON.parse(await file.text());
 if(data.version===2){if(!Array.isArray(data.entries)||data.entries.length>100||!data.progress||typeof data.progress!=='object')throw new Error('Invalid library backup.');const validated=[];
   for(const entry of data.entries){if(typeof entry.source!=='string'||typeof entry.filename!=='string')throw new Error('Invalid score entry.');const id=await scoreId(entry.partId?entry.source+'\nPiano part: '+entry.partId:entry.source);if(id!==entry.id)throw new Error('A score in this backup does not match its identity.');validated.push({...entry,id,score:parseMusicXML(entry.source,entry.filename,DOMParser,entry.partId||null)});}
   // Validate every state before writing anything.
   const states=[];for(const [id,incoming] of Object.entries(data.progress)){const entry=validated.find(e=>e.id===id)||library.find(e=>e.id===id);if(id!==BUILTIN&&!entry)throw new Error('Backup refers to an unknown score.');const piece=id===BUILTIN?builtinScore:entry.score;const parts=id===BUILTIN?builtinSections:makeSections(piece.measures);states.push([id,checkedState(incoming,parts,piece.measures)]);}
   for(const entry of validated){await storeScore(entry);if(!library.some(e=>e.id===entry.id))library.push(entry);}
   for(const [id,incoming] of states){const key=progressKey(id);let existing={};try{existing=JSON.parse(localStorage.getItem(key)||'{}');}catch{}for(const [k,r] of Object.entries(existing.records||{}))if(r.last>(incoming.records[k]?.last||0))incoming.records[k]=r;for(const p of ['learn','mix','polish','perform'])if((existing.stages?.[p]?.completed||0)>incoming.stages[p].completed)incoming.stages[p]=existing.stages[p];if((existing.practiceTiming?.activeSeconds||0)>(incoming.practiceTiming?.activeSeconds||0))incoming.practiceTiming=timingState(existing.practiceTiming);localStorage.setItem(key,JSON.stringify(incoming));}
   // Reload without saving the stale in-memory state over the restored one.
   loadState();activateScore(data.activeId===BUILTIN||library.some(e=>e.id===data.activeId)?data.activeId:activeId);
 }else{if(activeId!==BUILTIN)throw new Error('Select Black Is the Color before restoring its legacy backup.');const incoming=validateProgress(data);for(const [key,value] of Object.entries(incoming)){const existing=state.records[key];if(!existing||value.last>(existing.last||0))state.records[key]=value;}save();render();}
 $('importStatus').textContent='Backup restored. More recent practice records and higher completed-round counts were kept.';
 }catch(error){$('importStatus').textContent='Restore failed: '+error.message;}finally{event.target.value='';}}
function checkedState(value,parts,measures){
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid saved progress.');
 const records={};for(const [key,r] of Object.entries(value.records||{})){if(!/^\d+:(left|right|both)$/.test(key)||Number(key.split(':')[0])>=parts.length||!r||!Number.isInteger(r.attempts)||r.attempts<0||!Number.isInteger(r.clean)||r.clean<0||r.clean>r.attempts)throw new Error('Invalid practice record in backup.');records[key]={attempts:r.attempts,clean:r.clean,last:Number(r.last)||0,tempo:Number(r.tempo)||50,rating:[0,1,2].includes(r.rating)?r.rating:0};}
 const clean={records};for(const key of ['phase','hand','section','stages','targets','tempo','customStart','customEnd','volume','leftVolume','rightVolume','countBars','scoreSize','highlightMode','previewNext','showCueGuide','autoFollow','practiceTiming'])if(Object.hasOwn(value,key))clean[key]=value[key];
 const result=freshState(clean,parts,measures);result.practiceTiming=timingState(clean.practiceTiming);return result;
}
async function initializeLibrary(){try{library=(await listScores()).map(entry=>{try{return {...entry,score:parseMusicXML(entry.source,entry.filename,DOMParser,entry.partId||null)};}catch{return entry;}});refreshLibrary();const id=localStorage.getItem('piano-active-score');if(id&&id!==BUILTIN)activateScore(id);}catch{$('libraryStatus').textContent='Browser storage is unavailable. The built-in piece still works; imported scores require browser storage.';}}
initializeLibrary();


function renderLibraryList(){
 const list=$('libraryList');list.replaceChildren();
 for(const entry of [{id:BUILTIN,score:builtinScore},...library]){
  let saved={};try{saved=JSON.parse(localStorage.getItem(progressKey(entry.id))||'{}');}catch{}
  const phase=entry.id===activeId?state.phase:saved.phase,button=document.createElement('button'),title=document.createElement('strong'),detail=document.createElement('span');
  button.type='button';button.className='library-piece';button.setAttribute('aria-pressed',String(entry.id===activeId));title.textContent=entry.score.title;detail.textContent=entry.score.measures+' measures · '+({learn:'Separate hands',mix:'Hands together',polish:'Polishing',perform:'Whole piece'}[phase]||'Ready to start');button.append(title,detail);button.onclick=()=>activateScore(entry.id);list.append(button);
 }
}

$('downloadScore').onclick=()=>{const entry=library.find(e=>e.id===activeId);if(!entry)return;const url=URL.createObjectURL(new Blob([entry.source],{type:'application/vnd.recordare.musicxml+xml'})),a=document.createElement('a');a.href=url;a.download=score.title.replace(/[^a-z0-9]+/gi,'-')+'.musicxml';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

function renderEstimate(){
 const timing=state.practiceTiming||(state.practiceTiming=timingState()),estimate=estimatePractice(state);
 $('practiceEstimate').textContent=!estimate.remaining?'Practice plan completed':estimate.ready?'Estimated practice left: '+timeText(estimate.seconds):'Learning your pace';
 $('estimateDetail').textContent=!estimate.remaining?'Keep checking clean returns; completing a plan is not proof of mastery.':estimate.ready?'Range '+timeText(estimate.low)+' to '+timeText(estimate.high)+' · based on timed rounds and self-ratings.':'Time '+Math.max(0,3-timing.samples.length)+' more rated '+(3-timing.samples.length===1?'round':'rounds')+' (10+ seconds each).';
 $('practiceTimer').textContent=(timing.running?'Pause timer':'Start timer')+' · '+timeText(timing.activeSeconds);
 $('practiceTimer').setAttribute('aria-pressed',String(timing.running));
}
$('practiceTimer').onclick=()=>{state.practiceTiming.running=!state.practiceTiming.running;renderEstimate();save();};
let timerLast=Date.now(),timerSave=0;
setInterval(()=>{const now=Date.now(),elapsed=Math.min(2,(now-timerLast)/1000);timerLast=now;const t=state.practiceTiming||(state.practiceTiming=timingState());if(t.running&&!document.hidden){t.activeSeconds+=elapsed;if(!state.rated)t.roundSeconds+=elapsed;timerSave+=elapsed;if(timerSave>=5){save();timerSave=0;}}renderEstimate();},1000);
document.addEventListener('visibilitychange',()=>{if(document.hidden){state.practiceTiming.running=false;save();}timerLast=Date.now();renderEstimate();});
window.addEventListener('pagehide',()=>{state.practiceTiming.running=false;save();});
renderEstimate();

function choosePianoPart(parts,filename){
 return new Promise(resolve=>{const dialog=$('pianoPartDialog'),select=$('pianoPart');select.replaceChildren();for(const part of parts)select.append(new Option(part.name+' ('+part.id+')',part.id));$('pianoPartFile').textContent=filename;dialog.returnValue='cancel';dialog.onclose=()=>resolve(dialog.returnValue==='import'?select.value:null);dialog.showModal();});
}
$('removeScore').onclick=async()=>{const entry=library.find(e=>e.id===activeId);if(!entry)return;if(!confirm('Remove '+entry.score.title+' and its practice progress from this browser? Download a backup first if you want to keep it.'))return;try{await deleteScore(entry.id);activateScore(BUILTIN);library=library.filter(e=>e.id!==entry.id);localStorage.removeItem(progressKey(entry.id));refreshLibrary();$('libraryStatus').textContent=entry.score.title+' removed.';}catch(error){$('libraryStatus').textContent='Removal failed: '+error.message;}};
