import {score} from './score-data.js';
import {noteName,frequency,eventsFor,nextLesson,detectPitch,acceptPitch} from './engine.js';
const $=id=>document.getElementById(id);
const sections=[
 {name:'Opening pattern',start:1,end:2,goal:'Give the left-hand bass its full length. The right hand begins on the “and” of beat 1.',hint:'LH: E2 (2), then E2 (2) → B1 (5). RH: E3 with thumb; G3 + B3 with 3 + 5. For B minor: B2, then D3 + F♯3.'},
 {name:'Repeat & sustain',start:3,end:4,goal:'Keep the bass quiet and sustained while the same right-hand pattern moves above it.',hint:'LH: E2 with finger 2 in both bars. RH: eighth rest, E3, G3+B3, E3, G3+B3 quarter, E3 quarter.'},
 {name:'A minor to C and D',start:5,end:6,goal:'Respect the shared rest on beat 4 of measure 5. Prepare the low C before measure 6.',hint:'LH: A2 (1), rest on beat 4; C2 (5) → D2 (4). RH: A3, C4+E4. Next bar: G3, C4+E4, then F♯3, A3+D4.'},
 {name:'Walk down to E',start:7,end:8,goal:'Move the left hand A–G–E without rushing the chord changes.',hint:'LH: A2 (1) → G2 (2) → E2 (3). RH: A3 / C4+E4, then G3 / B3+E4; return to the E3 / G3+B3 pattern.'},
 {name:'The changing bass',start:9,end:10,goal:'Hear the difference between the held A and the E–D–C descent. RH block chords start with the bass in measure 10.',hint:'LH: A2 (1), then E2 (3), D2 (4), C2 (5). RH measure 10: E3+G3+B3, then D3+G3+B3; eighth rest, C3, E3+G3.'},
 {name:'A clean ending',start:11,end:12,goal:'Prepare the low E without an extra attack afterward. Let the final sound finish.',hint:'LH: E2 (2) → B1 (5), then E2 (2) → E1 (5). RH uses E minor and B minor in bar 11; bar 12 ends with a half rest. Shift the hand for E1; do not stretch.'},
 {name:'Join the first two phrases',start:4,end:6,goal:'Practise the E-minor-to-A-minor shift, then the rest and low C entry.',hint:'Start at bar 4, not the beginning. Keep counting through bar 5’s last beat. Prepare C2 with the pinky.'},
 {name:'Join the last two phrases',start:8,end:10,goal:'Move from sustained E to A, then place the E–D–C bass on the correct beats.',hint:'LH: bar 8 E2 (3), bar 9 A2 (1), bar 10 E2 (3) → D2 (4) → C2 (5). RH bar 10 changes to block chords.'},
 {name:'Full performance',start:1,end:12,goal:'Play both accompaniment hands through without stopping. Add the printed shaping and ritardando yourself.',hint:'Start quietly, count the rests, and keep going through a small slip. Mark one passage to revisit afterward rather than restarting.'}
];
const storageKey='black-is-the-color-practice-v1';let stored={};try{stored=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{}
let state={phase:stored.phase||'learn',section:stored.section||0,hand:stored.hand||'left',tempo:stored.tempo||50,round:stored.round||1,records:stored.records||{},rated:false};
if(!sections[state.section]||!['left','right','both'].includes(state.hand)||!['learn','mix','polish'].includes(state.phase))state={phase:'learn',section:0,hand:'left',tempo:50,round:1,records:{},rated:false};
let context,nodes=[],playTimer=null,playGeneration=0,playing=false,micStream=null,micSource=null,micGeneration=0,micTimer=null;
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveStatus').textContent='Saved on this device';}catch{$('saveStatus').textContent='Private browsing: progress may not save';}}
const section=()=>sections[state.section];
function handLabel(){return state.hand==='left'?'Left hand':state.hand==='right'?'Right hand':'Both piano hands';}
function rawMeasures(id){return score.abc.split('\n').filter(l=>l.startsWith('[V:'+id+']')).flatMap(l=>l.replace(/^\[V:[^\]]+\]\s*/,'').replace(/\|\]/g,'|').split('|').filter(x=>x.trim()));}
function excerpt(){const ids=state.hand==='left'?['LH']:state.hand==='right'?['RH']:['RH','LH'];let h='X:1\nT:Measures '+section().start+'–'+section().end+' · '+handLabel()+'\nM:4/4\nL:1/8\n%%score '+(ids.length===2?'{ RH LH }':ids[0])+'\n%%barsperstaff 2\n%%staffwidth 540\n';for(const id of ids)h+='V:'+id+' clef=bass name="'+id+'"\n';h+='K:Em\n';for(const id of ids){let bars=rawMeasures(id).slice(section().start-1,section().end).map(x=>x.replace(/!>[()]!/g,'').replace(/[()]/g,''));h+='[V:'+id+'] '+bars.join(' | ')+' |]\n';}return h;}
function fingers(e){if(e.voice==='left')return e.fingers.join(' + ');const n=e.notes.join(',');const single={52:'1',47:'1',57:'1',55:'1',54:'1',48:'1'};const chords={'55,59':'3 + 5','50,54':'3 + 5','60,64':'3 + 5','57,62':'2 + 5','59,64':'3 + 5','52,55,59':'1 + 3 + 5','50,55,59':'1 + 3 + 5','52,55':'3 + 5'};return e.notes.length===1?single[n]||'':chords[n]||'';}
function render(){
 stopAudio();stopMic();save();$('section').value=state.section;$('hand').value=state.hand;$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';
 document.querySelectorAll('[data-phase]').forEach(b=>{b.classList.toggle('selected',b.dataset.phase===state.phase);b.setAttribute('aria-pressed',String(b.dataset.phase===state.phase));});
 $('roundLabel').textContent='ROUND '+state.round+' · MEASURES '+section().start+'–'+section().end;
 $('lessonTitle').textContent=section().name+' · '+handLabel();$('lessonGoal').textContent=section().goal;
 $('recallPrompt').textContent=state.phase==='learn'?'With the score open: find the first note, its finger, and the first rest.':'With the score open: prepare this section’s first hand position, then start here.';$('hint').textContent=section().hint;$('hint').hidden=true;$('showHint').hidden=false;
 $('scoreWrap').hidden=false;
 try{ABCJS.renderAbc('notation',excerpt(),{responsive:'resize',staffwidth:540,add_classes:true,paddingright:10,paddingleft:10});}catch(error){$('notation').textContent='Notation could not render. Use the PDF download below.';console.error(error);}
 $('noteGuide').replaceChildren();const events=eventsFor(score,state.hand,section().start,section().end);
 for(let m=section().start;m<=section().end;m++){const row=document.createElement('div');row.className='note-row';const title=document.createElement('strong');title.textContent='Bar '+m;row.append(title);const text=document.createElement('div');for(const e of events.filter(e=>Math.floor(e.beat/4)+1===m)){const line=document.createElement('div');let beat=e.beat%4+1,where=Number.isInteger(beat)?'Beat '+beat:'“and” of '+Math.floor(beat);line.textContent=(state.hand==='both'?(e.voice==='left'?'LH ':'RH '):'')+where+': '+(e.notes.length?e.notes.map(noteName).join(' + '):'rest')+' · '+e.duration+' beat'+(e.duration===1?'':'s')+(e.notes.length&&fingers(e)?' · fingers '+fingers(e):'');text.append(line);}row.append(text);$('noteGuide').append(row);}
 $('feedback').textContent='A clean attempt means correct notes, the written rests, steady counting, and the chosen fingering.';state.rated=false;document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=false);renderProgress();
}
function renderProgress(){$('progress').replaceChildren();for(let i=0;i<6;i++){const row=document.createElement('div');row.className='progress-row';const name=document.createElement('span');name.textContent='mm. '+sections[i].start+'–'+sections[i].end;const val=document.createElement('span');val.className='dots';val.textContent=['left','right','both'].map(h=>(h==='left'?'L':h==='right'?'R':'Both')+' '+Math.min(2,state.records[i+':'+h]?.clean||0)+'/2').join(' · ');row.append(name,val);$('progress').append(row);}}
async function audioContext(){if(!context)context=new (window.AudioContext||window.webkitAudioContext)();if(context.state==='suspended')await context.resume();return context;}
function tone(n,start,duration,volume=.16){const ctx=context;const gain=ctx.createGain();gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.012);gain.gain.exponentialRampToValueAtTime(volume*.4,start+Math.min(.16,duration/2));gain.gain.exponentialRampToValueAtTime(.0001,start+Math.max(.04,duration));gain.connect(ctx.destination);const osc=ctx.createOscillator();osc.type='triangle';osc.frequency.value=frequency(n);osc.connect(gain);osc.start(start);osc.stop(start+duration+.02);nodes.push(osc);osc.onended=()=>{gain.disconnect();nodes=nodes.filter(x=>x!==osc);};}
function click(start,strong){tone(strong?88:81,start,.06,.07);}
function highlight(notes=[],hand='right'){document.querySelectorAll('#keyboard button').forEach(k=>{k.classList.toggle('lit',notes.includes(Number(k.dataset.note)));k.classList.toggle('left',hand==='left');});}
let previousMeasure=-1;function markMeasure(m){document.querySelectorAll("#notation .abcjs-note,#notation .abcjs-rest").forEach(n=>n.classList.toggle("is-current",m>=0&&n.classList.contains("abcjs-mm"+m)));if(m>=0&&m!==previousMeasure){const first=document.querySelector("#notation .is-current");if(first){const r=first.getBoundingClientRect();if(r.top<140||r.bottom>innerHeight-80)first.scrollIntoView({behavior:"smooth",block:"center"});}}previousMeasure=m;}
function stopAudio(){playGeneration++;playing=false;if(playTimer)clearInterval(playTimer);playTimer=null;for(const n of nodes)try{n.stop();}catch{}nodes=[];document.querySelectorAll('#beatBar span').forEach(s=>s.classList.remove('active'));highlight();markMeasure(-1);$('play').textContent='▶ Hear this part';$('playStatus').textContent='Read the score as you play. Use the hint or playback whenever you need it.';}
async function play(practice=false){
 stopMic();stopAudio();const generation=playGeneration;let ctx;try{ctx=await audioContext();}catch{$('playStatus').textContent='Audio is unavailable in this browser. Use the notation and count aloud.';return;}if(generation!==playGeneration)return;
 const seconds=60/state.tempo,total=(section().end-section().start+1)*4,offset=(section().start-1)*4,start=ctx.currentTime+.12,count=4;
 let ev=eventsFor(score,state.hand,section().start,section().end);if($('melody').checked&&!practice)ev=ev.concat(eventsFor(score,'melody',section().start,section().end));
 for(let b=0;b<count;b++)click(start+b*seconds,b===0);
 if(!practice){for(let i=0;i<ev.length;i++){const e=ev[i];if(e.tieEnd&&ev.some(p=>p.voice===e.voice&&p.tieStart&&p.beat+p.duration===e.beat))continue;let duration=e.duration;if(e.tieStart){const next=ev.find(p=>p.voice===e.voice&&p.tieEnd&&p.beat===e.beat+e.duration);if(next)duration+=next.duration;}for(const n of e.notes)tone(n,start+(count+e.beat-offset)*seconds,Math.max(.08,duration*seconds*.94),e.voice==='left'?.21:e.voice==='melody'?.12:.15);}}
 if($('metronome').checked)for(let b=0;b<total;b++)click(start+(count+b)*seconds,b%4===0);
 playing=true;$('play').textContent='Playing…';$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 playTimer=setInterval(()=>{const elapsed=(ctx.currentTime-start)/seconds;if(elapsed<0)return;let b=Math.floor(elapsed);document.querySelectorAll('#beatBar span').forEach((s,i)=>s.classList.toggle('active',i===b%4));if(elapsed<count){$('playStatus').textContent='Count in: '+(b+1)+' / 4';return;}let pos=elapsed-count;markMeasure(Math.floor(pos/4));$('playStatus').textContent=(practice?'Your turn · ':'Listen · ')+'measure '+(section().start+Math.floor(pos/4))+' · beat '+(Math.floor(pos%4)+1);if(!practice){let active=ev.filter(e=>pos>=e.beat-offset&&pos<e.beat-offset+e.duration);highlight(active.flatMap(e=>e.notes),state.hand);}if(pos>=total){const loop=$('loop').checked;stopAudio();$('playStatus').textContent='Finished. Let the sound settle, then rate your own attempt.';if(loop)play(practice);}},45);
}
function stopMic(){micGeneration++;if(micTimer)clearInterval(micTimer);micTimer=null;if(micSource)micSource.disconnect();micSource=null;if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;$('micStart').hidden=false;$('micStart').disabled=false;$('micStop').hidden=true;$('skipNote').hidden=true;$('micLabel').textContent='Microphone off';$('micTarget').textContent='—';$('micMeter').style.width='0';$('micStatus').textContent='Put your phone near the piano’s speaker. Use a clean piano sound and no sustain pedal for this check.';highlight();}
async function startMic(){
 if(state.hand!=='left'){state.hand='left';render();}stopAudio();stopMic();const generation=micGeneration;
 if(!navigator.mediaDevices?.getUserMedia){$('micStatus').textContent='Microphone access is unavailable. Open the HTTPS page in Safari or Chrome, or use the guide and self-checks.';return;}
 $('micStart').disabled=true;$('micStop').hidden=false;$('micStatus').textContent='Waiting for microphone permission…';let stream;
 try{const ctx=await audioContext();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(generation!==micGeneration){stream.getTracks().forEach(t=>t.stop());return;}micStream=stream;micSource=ctx.createMediaStreamSource(stream);const analyser=ctx.createAnalyser();analyser.fftSize=8192;micSource.connect(analyser);let buffer=new Float32Array(analyser.fftSize),stride=Math.max(1,Math.floor(ctx.sampleRate/12000)),down=new Float32Array(Math.floor(buffer.length/stride));
 const notes=eventsFor(score,'left',section().start,section().end).filter(e=>e.notes.length);let index=0,stableNote=null,stableSince=0,release=false,quiet=0,verified=0,skipped=0;
 $('micStart').hidden=true;$('micStop').hidden=false;$('skipNote').hidden=false;
 const target=()=>{let n=notes[index];$('micLabel').textContent='Note '+(index+1)+' of '+notes.length+' · pitch only';$('micTarget').textContent=noteName(n.notes[0])+' · finger '+n.fingers[0];$('micStatus').textContent='Play and hold this single note. Release fully before the next note.';highlight(n.notes,'left');markMeasure(Math.floor(n.beat/4)-section().start+1);$('playStatus').textContent='Mic target: '+noteName(n.notes[0])+' · finger '+n.fingers[0]+' · release fully between notes';};
 const advance=manual=>{if(manual)skipped++;else verified++;index++;stableNote=null;stableSince=0;release=true;quiet=0;if(index>=notes.length){stopMic();$('micLabel').textContent='Pitch round complete';$('micTarget').textContent=verified+' / '+notes.length+' detected';$('micStatus').textContent=(skipped?skipped+' manually skipped. ':'')+'Now play the section with its written rhythm. Pitch matches alone do not verify timing or fingers.';$('playStatus').textContent='Pitch round complete: '+verified+' / '+notes.length+' detected. Now practise the written rhythm.';markMeasure(-1);return;}target();};
 $('skipNote').onclick=()=>advance(true);target();$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 micTimer=setInterval(()=>{if(generation!==micGeneration)return;analyser.getFloatTimeDomainData(buffer);for(let i=0;i<down.length;i++)down[i]=buffer[i*stride];let d=detectPitch(down,ctx.sampleRate/stride);$('micMeter').style.width=Math.min(100,d.rms*600)+'%';let now=performance.now();if(d.midi===null){stableNote=null;stableSince=0;if(!quiet)quiet=now;if(now-quiet>100)release=false;return;}quiet=0;if(release){$('micStatus').textContent='Release the key and let it become quiet before the next note.';return;}if(d.midi!==stableNote){stableNote=d.midi;stableSince=now;}const expected=notes[index].notes[0];if(acceptPitch(d,expected,now-stableSince)){advance(false);}else if(d.confidence>.85&&now-stableSince>160){$('micStatus').textContent=d.midi===expected?'Hold the note steadily…':'Heard '+noteName(d.midi)+'. Find '+noteName(expected)+(Math.abs(d.midi-expected)===12?' in the indicated octave. If this is the correct key, the mic may be hearing a harmonic.':'.');}},70);
 }catch(error){if(stream)stream.getTracks().forEach(t=>t.stop());if(generation!==micGeneration)return;stopMic();$('micStatus').textContent=error.name==='NotAllowedError'?'Microphone permission was declined. You can keep practising with playback and self-checks.':'Could not start the microphone. Check your browser and microphone, or use self-checks.';}
}
for(let i=0;i<sections.length;i++){const o=document.createElement('option');o.value=i;o.textContent='mm. '+sections[i].start+'–'+sections[i].end+' · '+sections[i].name;$('section').append(o);}
$('section').onchange=()=>{state.section=Number($('section').value);state.round++;render();};$('hand').onchange=()=>{state.hand=$('hand').value;state.round++;render();};$('tempo').oninput=()=>{$('bpmLabel').textContent=$('tempo').value+' BPM';};$('tempo').onchange=()=>{stopAudio();state.tempo=Number($('tempo').value);save();};
document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{state.phase=b.dataset.phase;state.hand=state.phase==='learn'?'left':'both';state.section=state.phase==='polish'?6:0;state.round++;render();});
$('showHint').onclick=()=>{$('hint').hidden=false;$('showHint').hidden=true;};$('play').onclick=()=>play();$('stop').onclick=()=>{stopAudio();stopMic();};$('countIn').onclick=()=>play(true);$('micStart').onclick=startMic;$('micStop').onclick=stopMic;
document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{if(state.rated)return;stopAudio();stopMic();state.rated=true;const rating=Number(b.dataset.rating),key=state.section+':'+state.hand,prev=state.records[key]||{attempts:0,clean:0};prev.attempts++;prev.clean=rating===2?prev.clean+1:0;prev.last=Date.now();prev.tempo=state.tempo;prev.rating=rating;state.records[key]=prev;document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);$('feedback').textContent=rating===0?'Slow down 5 BPM, work only the rough change once, then switch sections. Return to this one after another round.':rating===1?'Keep the same tempo. Name the stumble, rehearse that transition once, and return after a different section.':prev.clean>=2?'Two clean returns logged. Try 5 BPM faster next time, or return tomorrow with the score.':'Clean attempt logged. Switch sections now, then test this one again from the score.';if(rating===0){state.tempo=Math.max(30,state.tempo-5);$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';}save();renderProgress();});
$('next').onclick=()=>{const n=nextLesson(state.records,state.phase,state,state.round);state.section=n.section;state.hand=n.hand;state.round++;render();$('lessonTitle').scrollIntoView({behavior:'smooth',block:'start'});};
$('exportProgress').onclick=()=>{const blob=new Blob([JSON.stringify({song:score.title,exported:new Date().toISOString(),...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='piano-practice-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let whites=0;for(let n=28;n<=76;n++){const black=[1,3,6,8,10].includes(n%12),key=document.createElement('button');key.dataset.note=n;key.textContent=noteName(n);key.setAttribute('aria-label','Play '+noteName(n));if(black){key.className='black';key.style.left=(whites*30-10)+'px';}else whites++;key.onclick=async()=>{if(micStream)return;$('playStatus').textContent='Keyboard reference: '+noteName(n);try{await audioContext();tone(n,context.currentTime+.01,.8,.2);highlight([n]);}catch{$('playStatus').textContent='Audio unavailable.';}};$('keyboard').append(key);}$('keyboard').style.minWidth=(whites*30)+'px';
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();stopMic();}});window.addEventListener('pagehide',()=>{stopAudio();stopMic();});render();
