import {timingState,recordTimedRound,estimatePractice,timeText,dailyState,addPractice,mergeDaily,addHistory,historyByDay,historyCSV,updateAccuracy} from './estimate.js?v=11';
import {MidiKeys,MidiConnection,midiTargets,matchesTarget,RhythmCheck,timingWindow} from './midi.js?v=8';
import {makeCues,cueState,stepBeat,alteredNoteHeads,spelledNotes,noteLabel} from './follower.js?v=14';
import {PianoSound, scheduleFrom, encodeWav} from './piano.js?v=5';
import {score as builtinScore} from './score-data.js';
import {freshState,rememberStage,switchStage,rateRound,chooseLesson,makeSections,recordKey,recordKeyPattern,nextLoopPoints,loopRange} from './practice.js?v=18';
import {renderWindow,contextMeasures,lineBars,firstSectionNode} from './view.js?v=3';
import {parseMusicXML,readMusicXMLFile,importedExcerpt} from './import-score.js?v=22';
import {BUILTIN,progressKey,scoreId,listScores,storeScore,deleteScore} from './library.js?v=11';
import {settings,settingByKey,groups,validate,actions,validKeys,presets,matchingPreset} from './settings.js?v=5';
let score=builtinScore, activeId=BUILTIN, library=[], starts=measureStarts(builtinScore);
import {noteName,frequency,eventsFor,detectPitch,acceptPitch,validateProgress,measureStarts,measureAt} from './engine.js?v=8';
const $=id=>document.getElementById(id);
const builtinSections=[
 {name:'Opening pattern',start:1,end:2,goal:'Give the left-hand bass its full length. The right hand begins on the “and” of beat 1.',hint:'LH: E2 (2), then E2 (2) → B1 (5). RH: E3 with thumb; G3 + B3 with 3 + 5. For B minor: B2, then D3 + F♯3.'},
 {name:'Repeat & sustain',start:3,end:4,goal:'Keep the bass quiet and sustained while the same right-hand pattern moves above it.',hint:'LH: E2 with finger 2 in both bars. RH: eighth rest, E3, G3+B3, E3, G3+B3 quarter, E3 quarter.'},
 {name:'A minor to C and D',start:5,end:6,goal:'Respect the shared rest on beat 4 of measure 5. Prepare the low C before measure 6.',hint:'LH: A2 (1), rest on beat 4; C2 (5) → D2 (4). RH: A3, C4+E4. Next bar: G3, C4+E4, then F♯3, A3+D4.'},
 {name:'Walk down to E',start:7,end:8,goal:'Move the left hand A–G–E without rushing the chord changes.',hint:'LH: A2 (1) → G2 (2) → E2 (3). RH: A3 / C4+E4, then G3 / B3+E4; return to the E3 / G3+B3 pattern.'},
 {name:'The changing bass',start:9,end:10,goal:'Hear the difference between the held A and the E–D–C descent. RH block chords start with the bass in measure 10.',hint:'LH: A2 (1), then E2 (3), D2 (4), C2 (5). RH measure 10: E3+G3+B3, then D3+G3+B3; eighth rest, C3, E3+G3.'},
 {name:'A clean ending',start:11,end:12,goal:'Prepare the low E without an extra attack afterward. Let the final sound finish.',hint:'LH: E2 (2) → B1 (5), then E2 (2) → E1 (5). RH uses E minor and B minor in bar 11; bar 12 ends with a half rest. Shift the hand for E1; do not stretch.'},
 {name:'Join the first two phrases',start:4,end:6,goal:'Practice the E-minor-to-A-minor shift, then the rest and low C entry.',hint:'Start at bar 4, not the beginning. Keep counting through bar 5’s last beat. Prepare C2 with the pinky.'},
 {name:'Join the last two phrases',start:8,end:10,goal:'Move from sustained E to A, then place the E–D–C bass on the correct beats.',hint:'LH: bar 8 E2 (3), bar 9 A2 (1), bar 10 E2 (3) → D2 (4) → C2 (5). RH bar 10 changes to block chords.'},
 {name:'Full performance',start:1,end:12,goal:'Play both accompaniment hands through without stopping. Add the printed shaping and ritardando yourself.',hint:'Start quietly, count the rests, and keep going through a small slip. Mark one passage to revisit afterward rather than restarting.'}
];
builtinSections.push({name:'Your measure range',start:1,end:2,goal:'Work on exactly the transition you need. Keep the score visible and the pulse steady.',hint:'Look at the starting bass note and prepare the right-hand chord before counting in.'});
let sections=builtinSections, storageKey=progressKey(activeId), state;
const pieceDefaults=()=>{try{return JSON.parse(localStorage.getItem('piano-piece-defaults')||'{}')||{};}catch{return {};}};
function loadState(){let stored={};try{stored=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{}if(activeId!==BUILTIN)sections=makeSections(score.measures,[1,2,4].includes(stored.sectionSize)?stored.sectionSize:2);state=freshState(stored,sections,score.measures,pieceDefaults());if(activeId===BUILTIN)state.sectionSize=2;if(!Object.hasOwn(stored,'rampTarget')&&score.tempo)state.rampTarget=validate('rampTarget',score.tempo);state.practiceTiming=timingState(stored.practiceTiming);}
loadState();
const today=()=>new Date().toLocaleDateString('en-CA');
let daily=dailyState();try{daily=dailyState(JSON.parse(localStorage.getItem('piano-daily')||'{}'));}catch{}
function saveDaily(){try{localStorage.setItem('piano-daily',JSON.stringify(daily));}catch{}}
let midiPractice=null,midiRhythm=null;
let cues=[],cueNodes=new Map(),followLine=null;
let piano,transport=null,positionBeat=0,loopPass=1;
let context,playTimer=null,playGeneration=0,playing=false,micStream=null,micSource=null,micTone=null,micGeneration=0,micTimer=null;
function save(){rememberStage(state);try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveStatus').textContent='Saved on this device';}catch{$('saveStatus').textContent='Private browsing: progress may not save';}}
const section=()=>sections[state.section];
// Measures may change length, so positions go through each measure's absolute start in quarter-note beats.
const barAt=beat=>measureAt(starts,beat),beatIn=beat=>beat-starts[barAt(beat)-1];
const sectionStart=()=>starts[section().start-1],sectionLength=()=>starts[section().end]-sectionStart();
function meterOf(m){const type=Number((score.meters?.[m-1]||score.meter||'4/4').split('/')[1]),pulse=Math.min(1,4/type),length=starts[m]-starts[m-1];return {length,pulse,pulses:Math.round(length/pulse)};}
// Beat indicator for one measure: "1 & 2 &" with eighth-note clicks in simple meters, and accents on
// each dotted-quarter group in compound meters. Returns the length of one box in quarter beats.
function beatBarFor(meter){const eighths=state.metronomeSub==='eighth'&&meter.pulse===1,step=eighths?.5:meter.pulse,count=Math.round(meter.length/step),compound=meter.pulse===.5&&count%3===0&&count>3,key=count+'|'+eighths+'|'+compound;if($('beatBar').dataset.key===key)return step;$('beatBar').dataset.key=key;$('beatBar').classList.toggle('subdivided',eighths);$('beatBar').replaceChildren(...Array.from({length:count},(_,i)=>{const b=document.createElement('span');b.textContent=eighths?(i%2?'&':i/2+1):i+1;b.classList.toggle('accent',compound?i%3===0:!eighths||i%2===0);return b;}));return step;}
function handLabel(){return state.hand==='left'?'Left hand':state.hand==='right'?'Right hand':'Both piano hands';}
function rawMeasures(id){return score.abc.split('\n').filter(l=>l.startsWith('[V:'+id+']')).flatMap(l=>l.replace(/^\[V:[^\]]+\]\s*/,'').replace(/\|\]/g,'|').split('|').filter(x=>x.trim()));}
function largeScore(){return state.scoreSize==='large'||window.matchMedia('(max-width:600px)').matches;}
const scoreWindow=()=>renderWindow(score.measures,section(),state);
// Printed bar number: imports with written-out repeats show which time through.
const measureLabel=m=>score.printedMeasures?.[m-1]??String(m);
// Wider staves only when more than two measures share a line; abcjs scales the SVG to the container.
let renderedLineBars=null,renderedAbc=null,scrolledSection=null;
// The score scrolls inside #scoreWrap when its height is limited, otherwise the page scrolls.
const scoreScroller=()=>{const wrap=$('scoreWrap');return wrap.scrollHeight>wrap.clientHeight+1&&getComputedStyle(wrap).overflowY!=='visible'?wrap:null;};
const scrollBehavior=()=>matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';
function revealNodes(nodes,force=false){if(!nodes.length)return;const rects=nodes.map(n=>n.getBoundingClientRect()),top=Math.min(...rects.map(r=>r.top)),bottom=Math.max(...rects.map(r=>r.bottom)),wrap=scoreScroller();
 if(wrap){const box=wrap.getBoundingClientRect();if(force||top<box.top+8||bottom>box.bottom-8)wrap.scrollBy({top:top-box.top-24,behavior:scrollBehavior()});return;}
 const toolbar=document.querySelector('.toolbar').getBoundingClientRect(),safeTop=Math.max(90,Math.min(innerHeight*.35,toolbar.bottom+16));
 if(top<safeTop||bottom>innerHeight-60)window.scrollBy({top:top-safeTop-35,behavior:scrollBehavior()});}
// Bring the section's first system into view whenever the section itself changes.
const sectionKey=()=>activeId+'|'+state.phase+'|'+section().start+'-'+section().end;
function scrollToSection(w){const key=sectionKey();if(key===scrolledSection)return;scrolledSection=key;if(!state.followSection||state.scoreView==='section')return;const first=firstSectionNode($('notation'),w,section());if(!first)return;const line=first.getAttribute('class').match(/abcjs-l\d+/)?.[0];revealNodes(line?[...$('notation').querySelectorAll('.'+line)]:[first],true);followLine=line;}
function layout(w){renderedLineBars=largeScore()?1:lineBars(state.barsPerLine,innerWidth);const bars=Math.min(renderedLineBars,w.end-w.start+1);return {bars,width:largeScore()?300:bars>2?Math.max(540,$('notation').clientWidth-20):540};}
function excerpt(w,{bars,width}){if(score.imported)return importedExcerpt(score,state.hand,w.start,w.end,largeScore(),{bars,width,expression:state.showExpression});const ids=state.hand==='left'?['LH']:state.hand==='right'?['RH']:['RH','LH'];let h='X:1\nT:Measures '+w.start+'–'+w.end+' · '+handLabel()+'\nM:4/4\nL:1/8\n%%score '+(ids.length===2?'{ RH LH }':ids[0])+'\n%%barsperstaff '+bars+'\n%%staffwidth '+width+'\n%%titlefont Georgia 16\n%%stretchlast 1\n%%measurenb 0\n%%setbarnb 2\n';for(const id of ids)h+='V:'+id+' clef=bass name="'+id+'"\n';h+='K:Em\n';for(const id of ids){let bars=rawMeasures(id).slice(w.start-1,w.end).map(x=>x.replace(/!>[()]!/g,'').replace(/[()]/g,''));h+='[V:'+id+'] '+bars.join(' | ')+' |]\n';}return h;}
// abcjs 6.6.4 numbers systems only when %%setbarnb is not 1 and miscounts later systems,
// so excerpts always set 2 and each system is labelled here from its measure class.
function decorateScore(w){const n=$('notation');n.style.setProperty('--dim',state.contextDim/100);n.querySelectorAll('.context').forEach(e=>e.classList.remove('context'));drawFlags(w);drawHeat(w);for(const t of n.querySelectorAll('.abcjs-bar-number'))t.textContent=measureLabel(w.start+Number(t.getAttribute('class').match(/abcjs-mm(\d+)/)[1]));for(const m of contextMeasures(w,section()))n.querySelectorAll('.abcjs-mm'+(m-w.start)).forEach(e=>e.classList.add('context'));applyMemorize(w);}
function fingers(e){if(score.imported)return e.fingers.filter(Boolean).join(' + ');if(e.voice==='left')return e.fingers.join(' + ');const n=e.notes.join(',');const single={52:'1',47:'1',57:'1',55:'1',54:'1',48:'1'};const chords={'55,59':'3 + 5','50,54':'3 + 5','60,64':'3 + 5','57,62':'2 + 5','59,64':'3 + 5','52,55,59':'1 + 3 + 5','50,55,59':'1 + 3 + 5','52,55':'3 + 5'};return e.notes.length===1?single[n]||'':chords[n]||'';}
function render(){
 renderEstimate();
 stopAudio();stopMic();const custom=sections.length-1;sections[custom].start=state.customStart||1;sections[custom].end=state.customEnd||Math.min(2,score.measures);if(state.phase==='perform')state.section=sections.length-2;save();$('section').disabled=state.phase==='perform';$('applyRange').disabled=state.phase==='perform';$('section').options[custom].textContent='mm. '+sections[custom].start+'-'+sections[custom].end+' · Your measure range';$('section').value=state.section;$('hand').value=state.hand;$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';for(const name of ['volume','leftVolume','rightVolume']){$(name).value=state[name]??75;$(name+'Label').textContent=$(name).value+'%';}$('sectionNotes').value=state.notes[recordKey(state,state.section,state.hand)]||'';$('notesScope').textContent=section().name+' · '+handLabel();$('rangeStart').value=section().start;$('rangeEnd').value=section().end;$('seek').max=sectionLength();beatBarFor(meterOf(section().start));updatePosition(0);
 document.querySelectorAll('[data-phase]').forEach(b=>{b.classList.toggle('selected',b.dataset.phase===state.phase);b.setAttribute('aria-pressed',String(b.dataset.phase===state.phase));});
 $('roundLabel').textContent=roundText();
 $('lessonTitle').textContent=section().name+' · '+handLabel();$('lessonGoal').textContent=section().goal;
 $('recallPrompt').textContent=state.phase==='learn'?'With the score open: find the first note, its finger, and the first rest.':'With the score open: prepare this section’s first hand position, then start here.';$('hint').textContent=section().hint;$('hint').hidden=true;$('showHint').hidden=false;
 $('scoreWrap').hidden=false;$('cueGuide').hidden=!state.showCueGuide;syncSettings();document.body.classList.toggle('print-note-names',state.printNoteNames);placeKeyboard();
 const record=state.records[recordKey(state,state.section,state.hand)];$('autoHintLine').hidden=!(state.autoHint&&state.phase!=='perform'&&(record?.attempts||0)<3);$('autoHintLine').textContent='Starting hint: '+section().hint;
 document.body.classList.toggle('short-excerpt',state.scoreView==='section'&&section().end-section().start<2);
 document.body.dataset.scoreHeight=state.scoreHeight==='auto'?(document.body.classList.contains('focus-mode')||matchMedia('(max-width:600px)').matches?'half':'fit'):state.scoreHeight;
 try{const w=scoreWindow(),size=layout(w),abc=excerpt(w,size),text=document.body.classList.contains('focus-mode')?abc.replace(/^T:.*\n/m,''):abc;
 // Only re-engrave when the notation itself changes; a new section only changes dimming, cues and scroll.
 if(text+'|'+size.width!==renderedAbc||!$('notation').querySelector('svg')){const started=performance.now();ABCJS.renderAbc('notation',text,{responsive:'resize',staffwidth:size.width,add_classes:true,paddingright:10,paddingleft:10});renderedAbc=text+'|'+size.width;if(state.scoreView==='piece'&&performance.now()-started>400)$('libraryStatus').textContent='This long score takes a moment to draw. For faster section changes choose Show: measures around the section.';}
 decorateScore(w);bindCues(w);drawNoteNames();showLoop();scrollToSection(w);}catch(error){renderedAbc=null;$('notation').textContent='Notation could not render. Use the PDF download below.';console.error(error);}
 $('noteGuide').replaceChildren();const events=eventsFor(score,state.hand,section().start,section().end);
 for(let m=section().start;m<=section().end;m++){const row=document.createElement('div');row.className='note-row';const title=document.createElement('strong');title.textContent='Bar '+measureLabel(m);row.append(title);const text=document.createElement('div');for(const e of events.filter(e=>barAt(e.beat)===m)){const line=document.createElement('div');let beat=beatIn(e.beat)+1,where=Number.isInteger(beat)?'Beat '+beat:'Beat '+Number(beat.toFixed(3));line.textContent=(state.hand==='both'?(e.voice==='left'?'LH ':'RH '):'')+where+': '+(e.notes.length?e.notes.map(noteName).join(' + '):'rest')+' · '+e.duration+' beat'+(e.duration===1?'':'s')+(e.notes.length&&fingers(e)?' · fingers '+fingers(e):'');text.append(line);}row.append(text);$('noteGuide').append(row);}
 $('feedback').textContent=state.rated?'This round is logged. Choose the next round button below when you are ready.':'A clean attempt means correct notes, the written rests, steady counting, and the chosen fingering.';document.querySelectorAll('[data-rating]').forEach(b=>b.disabled=!!state.rated);$('next').textContent=state.phase==='perform'?'Start another play-through →':'Next practice round →';renderProgress();renderPlan();
}
function renderProgress(){$('progress').replaceChildren();for(let i=0;i<Math.ceil(score.measures/state.sectionSize);i++){const row=document.createElement('div');row.className='progress-row';const name=document.createElement('span');name.textContent='mm. '+sections[i].start+'–'+sections[i].end+(state.flags.some(m=>m>=sections[i].start&&m<=sections[i].end)?' ⚑':'');const val=document.createElement('span');val.className='dots';val.textContent=['left','right','both'].map(h=>(h==='left'?'L':h==='right'?'R':'Both')+' '+Math.min(2,state.records[recordKey(state,i,h)]?.clean||0)+'/2').join(' · ');row.append(name,val);$('progress').append(row);}}
async function audioContext(){if(!context){context=new (window.AudioContext||window.webkitAudioContext)();piano=new PianoSound(context);}if(context.state==='suspended')await context.resume();piano.volume((state.volume??75)/100);return context;}
function click(start,strong){piano.click(start,strong);}
function clockText(beats){let sec=Math.max(0,Math.round(beats*60/state.tempo));return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');}
function updatePosition(beat){const total=sectionLength(),span=loopRange(activeLoop(),total);positionBeat=Math.max(span.a,Math.min(span.b,beat));const m=Math.min(barAt(sectionStart()+positionBeat),section().end),flagged=state.flags.includes(m);$('flagMeasure').setAttribute('aria-pressed',String(flagged));$('flagMeasure').textContent=(flagged?'⚑ Unflag measure ':'⚑ Flag measure ')+m;$('seek').value=positionBeat;$('seek').setAttribute('aria-valuetext','Measure '+Math.min(barAt(sectionStart()+positionBeat),section().end)+', beat '+(Math.floor(beatIn(sectionStart()+positionBeat))+1));$('timeLabel').textContent=clockText(positionBeat)+' / '+clockText(total);}
function selectedEvents(){let events=eventsFor(score,state.hand,section().start,section().end);if($('melody').checked)events=events.concat(eventsFor(score,'melody',section().start,section().end));return events;}
function voiceLevel(voice){return voice==='left'?(state.leftVolume??70)/100:voice==='right'?(state.rightVolume??80)/100:.65;}
function highlight(events=[]){const lit=new Set(events.flatMap(e=>e.notes)),left=new Set(events.filter(e=>e.voice==='left').flatMap(e=>e.notes));document.querySelectorAll('#keyboard button').forEach(k=>{const n=Number(k.dataset.note);k.classList.toggle('lit',lit.has(n));k.classList.toggle('left',left.has(n));});}
// Every rendered note is a cue; only those inside the section drive highlighting and stepping.
// Tapping a dimmed context note turns its measure into a one-bar practice range.
function bindCues(w){
 const first=sectionStart(),last=starts[section().end],all=makeCues(eventsFor(score,state.hand,w.start,w.end),state.hand,w.start,starts);cueNodes=new Map();
 cues=all.filter(c=>c.beat>=first-1e-6&&c.beat<last-1e-6);
 const inside=new Set(cues);
 for(const cue of all){const node=$('notation').querySelector(cue.selector);if(!node)throw new Error('Score cue is missing: '+cue.selector);cueNodes.set(cue,node);node.dataset.beat=cue.beat;node.dataset.voice=cue.voice;node.style.cursor='pointer';node.style.pointerEvents='bounding-box';let pressTimer=0,longPress=false;node.onpointerdown=()=>{longPress=false;if(!inside.has(cue))return;clearTimeout(pressTimer);pressTimer=setTimeout(()=>{longPress=true;setLoopPoint(cue);},550);};node.onpointerup=node.onpointerleave=()=>clearTimeout(pressTimer);node.onclick=event=>{if(longPress){longPress=false;return;}if(!inside.has(cue))return practiceMeasure(barAt(cue.beat));if(event.shiftKey)setLoopPoint(cue);else seekTo(cue.beat-first);};
 const altered=alteredNoteHeads(cue,score.measureKeys?.[barAt(cue.beat)-1]??0);for(const head of node.querySelectorAll('.abcjs-notehead')){const name=(head.getAttribute('data-name')||'').replace(/^[=^_]+/,'');const pitch=altered.find(p=>p.name===name);if(pitch&&!head.classList.contains('altered-pitch')){head.classList.add('altered-pitch','altered-'+pitch.kind);head.setAttribute('aria-label',pitch.label);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=pitch.label;head.append(title);}}
 }
}
function cueText(list){return list.length?list.map(e=>(e.voice==='left'?'LH: ':'RH: ')+(e.notes.length?e.notes.map(noteName).join(' + ')+(fingers(e)?' · fingers '+fingers(e):''):'rest')).join(' | '):'End of section';}
function markNotes(beat){
 const at=beat<0?{current:[],next:[]}:cueState(cues,beat),mode=state.highlightMode;
 const m=barAt(beat);highlight(at.current);const upcoming=new Set(state.showKeyboard?at.next.flatMap(e=>e.notes):[]);document.querySelectorAll('#keyboard button').forEach(k=>k.classList.toggle('is-next',upcoming.has(Number(k.dataset.note))));
 for(const [cue,node] of cueNodes){node.classList.toggle('is-current',beat>=0&&(mode==='notes'?at.current.includes(cue):mode==='measure'&&barAt(cue.beat)===m));node.classList.toggle('is-next',beat>=0&&state.outlineNext&&at.next.includes(cue));}
 $('cueNow').textContent=beat<0?'Press Play or step through the score.':cueText(at.current);$('cueNext').textContent=beat<0?'Your next notes and fingerings will appear here.':cueText(at.next);
 if(beat<0){followLine=null;return;}
 const nodes=at.current.map(c=>cueNodes.get(c)).filter(Boolean);if(!nodes.length||!state.autoFollow)return;
 const line=nodes[0].getAttribute('class').match(/abcjs-l\d+/)?.[0];if(line===followLine)return;followLine=line;
 revealNodes(nodes);
}
function markMeasure(m){markNotes(m<0?-1:(sectionStart()+positionBeat));}
function seekTo(at){const was=playing,practice=transport?.practice??false;stopAudio(false);stopMic();updatePosition(at);transport={practice,paused:true};markNotes(sectionStart()+positionBeat);$('pause').disabled=false;$('pause').textContent='Resume';$('playStatus').textContent='Ready at measure '+Math.min(barAt(sectionStart()+positionBeat),section().end)+'. Press Resume to continue.';if(was)play(practice,positionBeat,true);}
function stopAudio(reset=true){stopMidiPractice();cancelTap();playGeneration++;playing=false;if(playTimer)clearInterval(playTimer);playTimer=null;piano?.stop();document.querySelectorAll('#beatBar span').forEach(s=>s.classList.remove('active'));highlight();markMeasure(-1);$('play').textContent='▶ Hear this part';$('pause').disabled=true;$('pause').textContent='Pause';if(reset){transport=null;updatePosition(0);}$('playStatus').textContent='Read the score as you play. Use the hint or playback whenever you need it.';}
async function play(practice=false,from=positionBeat,resuming=false,looping=false){
 if(looping)loopPass++;else if(!resuming)loopPass=1;
 state.practiceTiming.running=true;renderEstimate();
 stopMic();stopAudio(false);const generation=playGeneration;const total=sectionLength(),span=loopRange(activeLoop(),total);if(from<span.a-1e-6||from>=span.b-1e-6)from=span.a;
 let ctx;try{ctx=await audioContext();if(!practice){$('playStatus').textContent='Loading grand piano…';await piano.load(selectedEvents().flatMap(e=>e.notes),(done,all)=>{if(generation!==playGeneration)return;$('soundState').textContent=done===all?'Grand piano loaded':'Loading piano '+done+'/'+all;});}}catch(error){if(generation===playGeneration){$('soundState').textContent='Piano could not load';$('playStatus').textContent='Could not load the piano recordings. Check your connection and press Play to retry. The score is still available.';}return;}if(generation!==playGeneration)return;
 const seconds=60/state.tempo,offset=sectionStart(),start=ctx.currentTime+.12,lead=meterOf(section().start),count=resuming?0:(state.countBars??1)*lead.length;
 const events=selectedEvents();for(let b=0;b<count/lead.pulse-1e-9;b++)click(start+b*lead.pulse*seconds,b%lead.pulses===0);
 if(!practice)for(const e of scheduleFrom(events,offset+from,offset+span.b))for(const n of e.notes)piano.note(n,start+(count+e.at)*seconds,e.length*seconds,voiceLevel(e.voice),e.voice==='left'?-.15:e.voice==='right'?.15:0);
 // Metronome patterns: every click, only each measure's first beat, or silent every second measure.
 if($('metronome').checked)for(let m=section().start;m<=section().end;m++){if(state.metronomeMode==='silent'&&(m-section().start)%2)continue;const {pulse}=meterOf(m),tick=state.metronomeSub==='eighth'?Math.min(pulse,.5):pulse;for(let t=0;starts[m-1]+t<starts[m]-1e-6;t+=tick){if(state.metronomeMode==='accents'&&t>0)break;const at=starts[m-1]+t-offset;if(at>=from-1e-6&&at<span.b-1e-6)click(start+(count+at-from)*seconds,t===0);}}
 transport={practice,start,count,seconds,from,total:span.b,paused:false};playing=true;$('play').textContent='Playing…';$('pause').disabled=false;$('pause').textContent='Pause';if(state.autoFollow&&!document.body.classList.contains('focus-mode'))$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 playTimer=setInterval(()=>{if(generation!==playGeneration)return;const elapsed=(ctx.currentTime-start)/seconds;if(elapsed<0)return;if(elapsed<count){const b=Math.floor(elapsed/lead.pulse),step=beatBarFor(lead),tick=Math.floor(elapsed/step+1e-9),ticks=Math.round(lead.length/step);document.querySelectorAll('#beatBar span').forEach((s,i)=>s.classList.toggle('active',i===tick%ticks));$('playStatus').textContent='Count in: '+(b%lead.pulses+1)+' / '+lead.pulses+(count>lead.length?' · bar '+(Math.floor(b/lead.pulses)+1):'');return;}let pos=elapsed-count+from;if(pos>=span.b){const loops=$('loop').value,loop=!midiRhythm&&!tapCheck&&(loops==='forever'||loopPass<Number(loops));finishMidiRhythm();finishTap();clearInterval(playTimer);playTimer=null;playing=false;transport=null;$('play').textContent='▶ Hear this part';$('pause').disabled=true;document.querySelectorAll('#beatBar span').forEach(s=>s.classList.remove('active'));highlight();markMeasure(-1);updatePosition(span.b);$('playStatus').textContent='Finished. Let the last piano note settle, then rate your own attempt.';if(loop)setTimeout(()=>{if(generation!==playGeneration)return;if(state.loopAccelerate&&state.tempo<state.rampTarget){state.tempo=Math.min(state.rampTarget,state.tempo+state.tempoStep);$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';save();}play(practice,span.a,false,true);},300);return;}updatePosition(pos);markNotes(offset+pos);const bar=barAt(offset+pos),meter=meterOf(bar),step=beatBarFor(meter);document.querySelectorAll('#beatBar span').forEach((s,i)=>s.classList.toggle('active',i===Math.floor((offset+pos-starts[bar-1])/step+1e-9)));$('playStatus').textContent=(practice?'Your turn · ':'Listen · ')+'measure '+bar+' · beat '+(Math.floor(beatIn(offset+pos))+1)+($('loop').value==='off'?'':' · pass '+loopPass+($('loop').value==='forever'?'':' of '+$('loop').value)+(state.loopAccelerate?' · ♩ = '+state.tempo:''));const active=events.filter(e=>offset+pos>=e.beat&&offset+pos<e.beat+e.duration);highlight(active);},45);
}
function pausePlayback(){if(!transport)return;if(transport.paused){play(transport.practice,positionBeat,true);return;}const current=transport,beat=Math.max(current.from,Math.min(current.total,(context.currentTime-current.start)/current.seconds-current.count+current.from));stopAudio(false);transport={...current,paused:true};updatePosition(beat);markMeasure(0);$('pause').disabled=false;$('pause').textContent='Resume';$('playStatus').textContent='Paused. The score stays at your place.';}
function stopMic(){micGeneration++;if(micTimer)clearInterval(micTimer);micTimer=null;if(micSource)micSource.disconnect();micSource=null;if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;micTone?.stop();micTone=null;$('micStart').hidden=false;$('micStart').disabled=false;$('micTest').disabled=false;$('micHeard').textContent='Heard: –';$('micStop').hidden=true;$('skipNote').hidden=true;$('micLabel').textContent='Microphone off';$('micTarget').textContent='Ready';$('micMeter').style.width='0';$('micStatus').textContent='Put your phone near the piano’s speaker. Use a clean piano sound and no sustain pedal for this check.';highlight();}
// A silent fundamental-plus-harmonics tone into the same analyser: verifies downsampling, pitch
// detection, the release gate and target advance with no microphone or permission prompt.
function testToneSource(ctx){
 const out=ctx.createGain();out.gain.value=0;let timer=0;
 const oscs=[.16,.1,.045].map(level=>{const o=ctx.createOscillator(),g=ctx.createGain();g.gain.value=level;o.connect(g).connect(out);o.start();return o;});
 return {output:out,play(hz){clearTimeout(timer);out.gain.setValueAtTime(0,ctx.currentTime);timer=setTimeout(()=>{oscs.forEach((o,i)=>o.frequency.setValueAtTime(hz*(i+1),ctx.currentTime));out.gain.setValueAtTime(1,ctx.currentTime);},600);},stop(){clearTimeout(timer);oscs.forEach(o=>o.stop());out.disconnect();}};
}
async function startMic(testTone=false){
 const hand=state.hand==='both'?(testTone?'left':null):state.hand,handText=hand==='left'?'left-hand':'right-hand';
 if(!hand){$('micStatus').textContent='Choose one hand for the microphone check: set Practice to Left hand or Right hand.';return;}
 stopAudio();stopMic();const generation=micGeneration;
 if(!testTone&&!navigator.mediaDevices?.getUserMedia){$('micStatus').textContent='Microphone access is unavailable. Open the HTTPS page in Safari or Chrome, or use the guide and self-checks.';return;}
 $('micStart').disabled=true;$('micTest').disabled=true;$('micStop').hidden=false;$('micStatus').textContent=testTone?'Starting the built-in test tone…':'Waiting for microphone permission…';let stream;
 try{const ctx=await audioContext();
 if(testTone){micTone=testToneSource(ctx);micSource=micTone.output;}else{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(generation!==micGeneration){stream.getTracks().forEach(t=>t.stop());return;}micStream=stream;micSource=ctx.createMediaStreamSource(stream);}
 const analyser=ctx.createAnalyser();analyser.fftSize=8192;micSource.connect(analyser);let buffer=new Float32Array(analyser.fftSize),stride=Math.max(1,Math.floor(ctx.sampleRate/12000)),down=new Float32Array(Math.floor(buffer.length/stride));
 let notes=eventsFor(score,hand,section().start,section().end).filter(e=>e.notes.length);if(testTone)notes=notes.filter(n=>n.notes.length===1).slice(0,4);
 let index=0,stableNote=null,stableSince=0,release=false,quiet=0,verified=0,skipped=0,octaves=0,targetSince=0,lastHeard=null;const tolerance=testTone?'strict':display.micOctaveTolerance;
 $('micStart').hidden=true;$('micStop').hidden=false;$('skipNote').hidden=testTone;
 if(!notes.length){stopMic();$('micStatus').textContent='No single '+handText+' notes in this section.';return;}if(!testTone&&notes.some(n=>n.notes.length>1)){stopMic();$('micStatus').textContent='This passage has '+handText+' chords. Use MIDI or self-checks for chords.';return;}
 const target=()=>{let n=notes[index];targetSince=performance.now();$('micLabel').textContent=(testTone?'Test tone · ':'')+'Note '+(index+1)+' of '+notes.length+' · pitch only';$('micTarget').textContent=noteName(n.notes[0])+(n.fingers[0]?' · finger '+n.fingers[0]:'');$('micStatus').textContent=testTone?'Playing a built-in tone for '+noteName(n.notes[0])+'…':'Play and hold this single note. Release fully before the next note.';highlight([n]);markNotes(n.beat);$('playStatus').textContent='Mic target: '+noteName(n.notes[0])+(n.fingers[0]?' · finger '+n.fingers[0]:'')+' · release fully between notes';micTone?.play(frequency(n.notes[0]));};
 const advance=(manual,octave)=>{if(manual)skipped++;else verified++;if(octave)octaves++;index++;stableNote=null;stableSince=0;release=true;quiet=0;if(index>=notes.length){stopMic();if(testTone){$('micLabel').textContent='Self-test complete';$('micTarget').textContent=verified+' / '+notes.length;$('micStatus').textContent='Detection chain OK: '+verified+' / '+notes.length+'. The analyser, pitch detection and note advance work in this browser. Your microphone itself is checked with Start note check.';markMeasure(-1);return;}$('micLabel').textContent='Pitch round complete';$('micTarget').textContent=verified+' / '+notes.length+' detected';$('micStatus').textContent=(skipped?skipped+' manually skipped. ':'')+(octaves?octaves+' accepted with the octave uncertain. ':'')+'Now play the section with its written rhythm. Pitch matches alone do not verify timing or fingers.';$('playStatus').textContent='Pitch round complete: '+verified+' / '+notes.length+' detected. Now practice the written rhythm.';markMeasure(-1);return;}target();if(octave)$('micStatus').textContent='Octave uncertain, accepted. '+$('micStatus').textContent;};
 $('skipNote').onclick=()=>advance(true);target();if(state.autoFollow&&!document.body.classList.contains('focus-mode'))$('playStatus').scrollIntoView({behavior:'smooth',block:'start'});
 micTimer=setInterval(()=>{if(generation!==micGeneration)return;analyser.getFloatTimeDomainData(buffer);for(let i=0;i<down.length;i++)down[i]=buffer[i*stride];let d=detectPitch(down,ctx.sampleRate/stride);$('micMeter').style.width=Math.min(100,d.rms*600)+'%';let now=performance.now();
  if(d.midi!==null&&d.confidence>.85){lastHeard=d.midi;$('micHeard').textContent='Heard: '+noteName(d.midi)+' · '+(d.cents>0?'+':d.cents<0?'−':'±')+Math.abs(d.cents||0)+' cents';}else if(d.midi===null)$('micHeard').textContent='Heard: –';
  if(testTone&&now-targetSince>5000){const expected=notes[index].notes[0];stopMic();$('micLabel').textContent='Self-test failed';$('micTarget').textContent=verified+' / '+notes.length;$('micStatus').textContent='Detection failed at '+noteName(expected)+(lastHeard!==null?' (heard '+noteName(lastHeard)+')':' (no stable pitch)')+'. Pitch checking may not work in this browser.';return;}
  if(d.midi===null){stableNote=null;stableSince=0;if(!quiet)quiet=now;if(now-quiet>100)release=false;return;}quiet=0;if(release){if(!testTone)$('micStatus').textContent='Release the key and let it become quiet before the next note.';return;}if(d.midi!==stableNote){stableNote=d.midi;stableSince=now;}const expected=notes[index].notes[0],accepted=acceptPitch(d,expected,now-stableSince,tolerance);if(accepted){advance(false,accepted==='octave');}else if(!testTone&&d.confidence>.85&&now-stableSince>160){$('micStatus').textContent=d.midi===expected?'Hold the note steadily…':'Heard '+noteName(d.midi)+'. Find '+noteName(expected)+(Math.abs(d.midi-expected)===12?' in the indicated octave. If this is the correct key, the mic may be hearing a harmonic; Octave check in this panel can allow it.':'.');}},70);
 }catch(error){if(stream)stream.getTracks().forEach(t=>t.stop());if(generation!==micGeneration)return;stopMic();$('micStatus').textContent=error.name==='NotAllowedError'?'Microphone permission was declined. You can keep practicing with playback and self-checks.':testTone?'Could not start the test tone: '+error.message:'Could not start the microphone. Check your browser and microphone, or use self-checks.';}
}
function fillSelectors(){
 $('section').replaceChildren();for(let i=0;i<sections.length;i++){const o=new Option('mm. '+sections[i].start+'–'+sections[i].end+' · '+sections[i].name,i);$('section').append(o);}
 for(const id of ['rangeStart','rangeEnd']){$(id).replaceChildren();for(let i=1;i<=score.measures;i++)$(id).append(new Option(i,i));}
 $('pieceTitle').textContent=score.title;$('tempoMark').hidden=!score.tempo;$('markedTempoValue').textContent='Marked tempo ♩ = '+score.tempo;$('measureCount').textContent=score.measures+' measures';$('brandTitle').textContent=score.title;
 $('scoreNotes').textContent=score.imported?'Imported piano score. Printed fingerings are retained where supplied. Playback counts quarter-note beats.':'Both accompaniment staves use bass clef. Middle C = C4. The top melody is a separate part.';
 $('melody').checked=false;$('melody').parentElement.hidden=!!score.imported;
 document.querySelectorAll('a[href^="Black-Is-the-Color"]').forEach(a=>a.hidden=!!score.imported);
 $('libraryWarnings').textContent=(score.warnings||[]).join(' ');$('downloadScore').hidden=!score.imported;$('removeScore').hidden=!score.imported;
}
fillSelectors();
$('section').onchange=()=>{state.section=Number($('section').value);render();};$('hand').onchange=()=>{state.hand=$('hand').value;render();};$('tempo').oninput=()=>{$('bpmLabel').textContent=$('tempo').value+' BPM';};$('tempo').onchange=()=>{const was=playing,practice=transport?.practice,at=positionBeat;stopAudio(false);state.tempo=Number($('tempo').value);updatePosition(at);save();if(was)play(practice,at,true);};
document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{switchStage(state,b.dataset.phase);render();});
$('showHint').onclick=()=>{$('hint').hidden=false;$('showHint').hidden=true;};$('play').onclick=()=>play();$('pause').onclick=pausePlayback;$('stop').onclick=()=>{stopAudio();stopMic();};$('countIn').onclick=()=>play(true);$('micStart').onclick=()=>startMic();$('micTest').onclick=()=>startMic(true);$('micStop').onclick=stopMic;
document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{if(!rateRound(state))return;stopAudio();stopMic();const rating=Number(b.dataset.rating);state.history=addHistory(state.history,[Date.now(),['learn','mix','polish','perform'].indexOf(state.phase),state.section,['left','right','both'].indexOf(state.hand),rating,state.tempo,Math.round(state.practiceTiming.roundSeconds)]);if(state.phase!=='perform')recordTimedRound(state.practiceTiming,rating);renderEstimate();const key=recordKey(state,state.section,state.hand),prev=state.records[key]||{attempts:0,clean:0};prev.attempts++;prev.clean=rating===2?prev.clean+1:0;prev.last=Date.now();prev.tempo=state.tempo;prev.rating=rating;state.records[key]=prev;document.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);const step=state.tempoStep;$('feedback').textContent=rating===0?(state.autoSlow?'Slowed down '+step+' BPM. Work only the rough change once, then switch sections. Return to this one after another round.':'Work only the rough change once at a tempo you can control, then switch sections. Return to this one after another round.'):rating===1?'Keep the same tempo. Name the stumble, rehearse that transition once, and return after a different section.':prev.clean>=2?'Two clean returns logged. Try '+step+' BPM faster next time, or return tomorrow with the score.':'Clean attempt logged. Switch sections now, then test this one again from the score.';if(rating===0&&state.autoSlow){state.tempo=Math.max(30,state.tempo-step);$('tempo').value=state.tempo;$('bpmLabel').textContent=state.tempo+' BPM';}
 // Tempo ramp: the passage remembers its tempo, one step faster after every two clean rounds in a row.
 if(state.tempoRamp&&state.phase!=='perform'){prev.tempo=state.tempo;if(rating===2&&prev.clean>=2&&prev.clean%2===0&&state.tempo<state.rampTarget){prev.tempo=Math.min(state.rampTarget,state.tempo+step);$('feedback').textContent='Two clean rounds in a row. This passage comes back at ♩ = '+prev.tempo+' (target '+state.rampTarget+').';}}
 if(state.fadeHand!=='off'&&state.phase==='mix'&&rating===2){const name=state.fadeHand+'Volume';state[name]=Math.max(0,state[name]-20);$(name).value=state[name];$(name+'Label').textContent=state[name]+'%';$('feedback').textContent+=' '+(state.fadeHand==='left'?'Left':'Right')+'-hand playback is now '+state[name]+'%; play more of it yourself.';}
 save();renderProgress();renderPlan();});
$('next').onclick=()=>{if(!state.rated){$('feedback').textContent='Rate your attempt first to complete this round. Navigation never adds a round.';return;}Object.assign(state,chooseLesson(state,sections,score.measures));state.rated=false;if(state.tempoRamp&&state.phase!=='perform'){const r=state.records[recordKey(state,state.section,state.hand)];if(r?.tempo)state.tempo=validate('tempo',r.tempo);}state.practiceTiming.roundSeconds=0;state.practiceTiming.running=true;render();if(!document.body.classList.contains('focus-mode'))$('lessonTitle').scrollIntoView({behavior:'smooth',block:'start'});};
$('exportProgress').onclick=async()=>{save();try{const entries=await listScores();downloadJSON({version:2,activeId,entries,daily,settings:{device:display},progress:Object.fromEntries([BUILTIN,...entries.map(e=>e.id)].map(id=>[id,JSON.parse(localStorage.getItem(progressKey(id))||'{}')]))},'piano-repertoire-backup.json');$('importStatus').textContent='Library and progress backup downloaded.';}catch(error){$('importStatus').textContent='Backup failed: '+error.message;}};
async function playReference(n){if(micStream)return;$('playStatus').textContent='Keyboard reference: '+noteName(n);try{await audioContext();const generation=playGeneration;await piano.load([n]);if(generation!==playGeneration||micStream)return;piano.note(n,context.currentTime+.01,1,.75);highlight([{notes:[n]}]);}catch{$('playStatus').textContent='Audio unavailable.';}}
// The on-screen and computer keyboards play into the virtual MIDI input when it is selected.
const virtualHeld=new Set();let virtualOctave=0;
function virtualKey(n,on){if(midiConnection.input!==midiConnection.virtual||on===virtualHeld.has(n))return;if(on)virtualHeld.add(n);else virtualHeld.delete(n);midiConnection.virtual.send(on?[144,n,100]:[128,n,0]);}
const virtualCodes=['KeyA','KeyW','KeyS','KeyE','KeyD','KeyF','KeyT','KeyG','KeyY','KeyH','KeyU','KeyJ','KeyK'];
let whites=0;for(let n=28;n<=76;n++){const black=[1,3,6,8,10].includes(n%12),key=document.createElement('button');key.dataset.note=n;key.textContent=noteName(n);key.setAttribute('aria-label','Play '+noteName(n));if(black){key.className='black';key.style.left=(whites*30-10)+'px';}else whites++;key.onclick=()=>playReference(n);key.onpointerdown=()=>virtualKey(n,true);key.onpointerup=key.onpointerleave=()=>virtualKey(n,false);$('keyboard').append(key);}$('keyboard').style.minWidth=(whites*30)+'px';

// B1: note names drawn on each notehead from its written spelling; they dim and highlight with the note.
function drawNoteNames(){const n=$('notation'),NS='http://www.w3.org/2000/svg';n.querySelectorAll('.note-name').forEach(e=>e.remove());if(state.noteNames==='off')return;
 for(const [cue,node] of cueNodes){if(!cue.notes.length)continue;const spelled=spelledNotes(cue,score.measureKeys?.[barAt(cue.beat)-1]??0);
  for(const head of node.querySelectorAll('.abcjs-notehead')){const name=(head.getAttribute('data-name')||'').replace(/^[=^_]+/,''),p=spelled.find(s=>s.name===name);if(!p)continue;
   const box=head.getBBox(),g=document.createElementNS(NS,'g'),bg=document.createElementNS(NS,'rect'),text=document.createElementNS(NS,'text');g.setAttribute('class','note-name');g.setAttribute('aria-hidden','true');
   text.textContent=noteLabel(p,state.noteNames);for(const [k,v] of [['x',box.x+box.width/2],['y',box.y+box.height/2],['text-anchor','middle'],['dominant-baseline','central']])text.setAttribute(k,v);g.append(bg,text);node.append(g);
   const t=text.getBBox();for(const [k,v] of [['x',t.x-1.2],['y',t.y-.4],['width',t.width+2.4],['height',t.height+.8],['rx',2.5]])bg.setAttribute(k,v);}}}
// B2: the keyboard moves to a strip under the score and scrolls to the section's lowest note.
function placeKeyboard(){const strip=$('keyboardStrip'),wrap=$('keyboard').parentElement;strip.hidden=!state.showKeyboard;
 if(state.showKeyboard){if(wrap.parentElement!==strip)strip.append(wrap);const notes=eventsFor(score,state.hand,section().start,section().end).flatMap(e=>e.notes);if(notes.length){const key=document.querySelector('#keyboard [data-note="'+Math.max(28,Math.min(...notes))+'"]');if(key)requestAnimationFrame(()=>{wrap.scrollLeft=Math.max(0,key.offsetLeft-30);});}}
 else if(wrap.parentElement===strip)$('keyboardHome').before(wrap);}
function roundText(){return 'ROUND '+(state.completed+(state.rated?0:1))+' · MEASURES '+section().start+'–'+section().end+(state.tempoRamp&&state.phase!=='perform'?' · ♩ = '+state.tempo+' → TARGET '+state.rampTarget:'');}
// B3: tap each note start of the selected hand(s); scored like the MIDI timed check, without pitch.
let tapCheck=null;
function cancelTap(){if(!tapCheck)return;tapCheck=null;$('tapButton').disabled=true;$('tapResults').textContent='Rhythm tap cancelled because playback stopped or changed. Start again for a complete result.';}
function finishTap(){if(!tapCheck)return;const r=tapCheck.summary();recordAccuracy(tapCheck);tapCheck=null;$('tapButton').disabled=true;$('tapFeedback').textContent='';$('tapResults').textContent='Rhythm: '+r.onTime+' / '+r.expected+' on time; '+r.early+' early, '+r.late+' late, '+r.missed+' missed, '+r.extra+' extra taps. Checks when notes start, not pitches or how long they are held.';}
function tapNow(){if(!tapCheck||!transport||transport.paused)return;const absolute=(context.currentTime-transport.start)-transport.count*transport.seconds+(sectionStart()+transport.from)*transport.seconds,r=tapCheck.hit(null,absolute);$('tapFeedback').textContent=r.kind==='ignored'?'Wait for the count-in to finish.':r.kind==='extra'?'Extra tap. Keep the pulse going.':r.kind[0].toUpperCase()+r.kind.slice(1)+(r.delta?' ('+Math.round(Math.abs(r.delta)*1000)+' ms)':'')+'.';$('tapButton').classList.remove('pulse');void $('tapButton').offsetWidth;$('tapButton').classList.add('pulse');}
$('tapStart').onclick=async()=>{clearLoop();stopAudio();stopMic();$('tapResults').textContent='';state.countBars=Math.max(1,state.countBars);syncSettings();await play(true,0);if(!playing)return;tapCheck=new RhythmCheck(eventsFor(score,state.hand,section().start,section().end),state.tempo,$('midiStrictness').value,{pitchless:true});$('tapButton').disabled=false;$('tapButton').focus();$('tapFeedback').textContent='Count in, then tap each note start. Timing window: ±'+Math.round(tapCheck.window*1000)+' ms.';};
$('tapButton').onpointerdown=event=>{event.preventDefault();tapNow();};
// I1: trouble-spot flags, toggled for the measure at the playing position.
function drawFlags(w){const n=$('notation'),svg=n.querySelector('svg');n.querySelectorAll('.flag-marker').forEach(e=>e.remove());if(!svg)return;
 for(const m of state.flags){if(m<w.start||m>w.end)continue;const k=m-w.start,items=[...n.querySelectorAll('.abcjs-mm'+k+'.abcjs-v0')].filter(e=>!e.classList.contains('abcjs-bar-number'));if(!items.length)continue;const boxes=items.map(e=>e.getBBox()),text=document.createElementNS('http://www.w3.org/2000/svg','text');
  text.setAttribute('class','flag-marker abcjs-mm'+k);text.setAttribute('x',Math.min(...boxes.map(b=>b.x)));text.setAttribute('y',Math.min(...boxes.map(b=>b.y))-6);text.textContent='⚑';const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent='Flagged trouble spot, measure '+m;text.append(title);svg.append(text);}}
$('flagMeasure').onclick=()=>{const m=Math.min(barAt(sectionStart()+positionBeat),section().end);state.flags=state.flags.includes(m)?state.flags.filter(x=>x!==m):[...state.flags,m].sort((a,b)=>a-b);save();decorateScore(scoreWindow());updatePosition(positionBeat);renderProgress();$('playStatus').textContent=state.flags.includes(m)?'Measure '+m+' flagged. Passages containing it come back sooner.':'Flag removed from measure '+m+'.';};
// I2: loop points inside the section, cleared whenever the section changes.
let loopPoints={key:null};
const activeLoop=()=>loopPoints.key===sectionKey()?loopPoints:{};
const beatText=beat=>'measure '+barAt(sectionStart()+beat)+', beat '+(Math.floor(beatIn(sectionStart()+beat)+1e-6)+1);
function setLoopPoint(cue){const first=sectionStart();loopPoints={key:sectionKey(),...nextLoopPoints(activeLoop(),cue.beat-first,cue.beat+cue.duration-first)};stopAudio(false);transport=null;updatePosition(loopPoints.a);showLoop();$('playStatus').textContent=loopPoints.b==null?'Loop start set at '+beatText(loopPoints.a)+'. Shift-click or long-press a later note to set the end.':'Looping '+beatText(loopPoints.a)+' to '+beatText(loopPoints.b)+'. Play and Loop stay inside it.';}
function clearLoop(){if(!loopPoints.key)return;loopPoints={key:null};showLoop();updatePosition(0);}
function showLoop(){const n=$('notation'),points=activeLoop(),span=loopRange(points,sectionLength());n.querySelectorAll('.loop-bracket').forEach(e=>e.remove());$('clearLoop').hidden=points.a==null;$('seek').min=span.a;$('seek').max=span.b;if(points.a==null)return;
 const first=sectionStart(),lines=new Map();for(const [cue,node] of cueNodes){if(cue.beat<first+span.a-1e-6||cue.beat>=first+span.b-1e-6)continue;const line=node.getAttribute('class').match(/abcjs-l\d+/)?.[0],box=node.getBBox(),r=lines.get(line)||{x1:Infinity,x2:-Infinity,y:Infinity};r.x1=Math.min(r.x1,box.x);r.x2=Math.max(r.x2,box.x+box.width);r.y=Math.min(r.y,box.y);lines.set(line,r);}
 const svg=n.querySelector('svg');for(const r of lines.values()){const rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('class','loop-bracket');for(const [k,v] of [['x',r.x1-2],['y',r.y-12],['width',r.x2-r.x1+4],['height',3],['rx',1.5]])rect.setAttribute(k,v);svg?.append(rect);}}
$('clearLoop').onclick=()=>{stopAudio();clearLoop();$('playStatus').textContent='Loop points cleared. Playback covers the whole section again.';};
// A1: recent accuracy per measure from timed checks, drawn as a tint behind each measure.
function recordAccuracy(check){state.measureStats=updateAccuracy(state.measureStats,check.measureResults(barAt));save();if(state.heatmap)decorateScore(scoreWindow());}
function drawHeat(w){const n=$('notation'),svg=n.querySelector('svg'),NS='http://www.w3.org/2000/svg';n.querySelectorAll('.heat').forEach(e=>e.remove());$('clearHeat').hidden=!state.heatmap;if(!svg||!state.heatmap)return;
 for(const [m,stat] of Object.entries(state.measureStats)){const k=Number(m)-w.start;if(k<0||Number(m)>w.end)continue;const lines=new Map();
  for(const e of n.querySelectorAll('.abcjs-mm'+k)){if(e.matches('.abcjs-bar-number,.flag-marker'))continue;const line=e.getAttribute('class').match(/abcjs-l\d+/)?.[0];if(!line)continue;const b=e.getBBox(),r=lines.get(line)||{x1:Infinity,x2:-Infinity,y1:Infinity,y2:-Infinity};r.x1=Math.min(r.x1,b.x);r.x2=Math.max(r.x2,b.x+b.width);r.y1=Math.min(r.y1,b.y);r.y2=Math.max(r.y2,b.y+b.height);lines.set(line,r);}
  for(const r of lines.values()){const rect=document.createElementNS(NS,'rect'),title=document.createElementNS(NS,'title');rect.setAttribute('class','heat abcjs-mm'+k);for(const [a,v] of [['x',r.x1-3],['y',r.y1-4],['width',r.x2-r.x1+6],['height',r.y2-r.y1+8],['rx',3]])rect.setAttribute(a,v);rect.style.fill='hsl('+Math.round(stat.acc*120)+' 70% 48%)';title.textContent='Measure '+measureLabel(Number(m))+': '+Math.round(stat.acc*100)+'% on time in recent checks';rect.append(title);svg.insertBefore(rect,svg.firstChild);}}}
$('clearHeat').onclick=()=>{state.measureStats={};save();decorateScore(scoreWindow());$('playStatus').textContent='Accuracy colours cleared for this piece.';};
// A2: memorization hides the section's notes, beams and ties; barlines, rests and bar numbers stay.
function applyMemorize(w){const n=$('notation'),s=section(),record=state.records[recordKey(state,state.section,state.hand)],on=state.memorize==='always'||state.memorize==='after2'&&(record?.clean||0)>=2;n.querySelectorAll('.memorize').forEach(e=>e.classList.remove('memorize'));n.classList.toggle('memorizing',on);$('peek').hidden=!on;if(!on)return;
 for(let m=w.start;m<=w.end;m++){if(!state.memorizeAll&&(m<s.start||m>s.end))continue;n.querySelectorAll('.abcjs-mm'+(m-w.start)).forEach(e=>{if(e.matches('.abcjs-note,.abcjs-beam-elem,.abcjs-tie,.abcjs-slur,.abcjs-decoration,.abcjs-annotation'))e.classList.add('memorize');});}}
$('peek').onpointerdown=event=>{event.preventDefault();$('notation').classList.add('peek');};$('peek').onpointerup=$('peek').onpointerleave=()=>$('notation').classList.remove('peek');
// A4: practice history for this piece.
function renderHistory(){const panel=$('historyPanel');panel.hidden=!state.showHistory;if(panel.hidden)return;
 const days=historyByDay(state.history),max=Math.max(1,...days.map(d=>d.seconds)),total=days.reduce((t,d)=>({seconds:t.seconds+d.seconds,rounds:t.rounds+d.rounds,clean:t.clean+d.clean}),{seconds:0,rounds:0,clean:0});
 $('historyStrip').replaceChildren(...days.map(d=>{const bar=document.createElement('span');bar.style.height=(d.seconds?Math.max(8,Math.round(d.seconds/max*100)):3)+'%';bar.style.opacity=d.rounds?.35+.65*d.clean/d.rounds:.3;bar.title=d.date+': '+Math.round(d.seconds/60)+' min, '+d.rounds+' rated rounds, '+d.clean+' clean';return bar;}));
 $('historySummary').textContent='Last 30 days: '+Math.round(total.seconds/60)+' min timed, '+total.rounds+' rated round'+(total.rounds===1?'':'s')+(total.rounds?', '+Math.round(total.clean/total.rounds*100)+'% clean':'')+'. Taller bars are longer days; darker bars had more clean rounds.';
 const stages=['Learn','Mix','Polish','Whole piece'],hands=['Left','Right','Both'],ratings=['Slow retry','Close','Clean'];
 $('historyRows').replaceChildren(...state.history.slice(-12).reverse().map(([t,p,s,h,r,tempo])=>{const row=document.createElement('tr');for(const text of [new Date(t).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}),stages[p],sections[s]?.name||'Section '+(s+1),hands[h],ratings[r],tempo+' BPM']){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}return row;}));
 $('exportHistory').disabled=!state.history.length;}
function downloadText(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportHistory').onclick=()=>downloadText(historyCSV(state.history,s=>sections[s]?.name||'Section '+(s+1)),score.title.replace(/[^a-z0-9]+/gi,'-')+'-practice-history.csv','text/csv');
$('clearHistory').onclick=()=>{if(!confirm('Clear the practice history of '+score.title+'? Round counts and progress are kept.'))return;state.history=[];save();renderHistory();};
function practiceMeasure(m){if(state.phase==='perform')return;state.customStart=state.customEnd=m;state.section=sections.length-1;render();$('playStatus').textContent='Practicing measure '+m+' on its own. Choose a section to return.';}
$('applyRange').onclick=()=>{const start=Number($('rangeStart').value),end=Number($('rangeEnd').value);if(start>end){$('rangeError').textContent='The first measure must come before the last measure.';return;}$('rangeError').textContent='';state.customStart=start;state.customEnd=end;state.section=sections.length-1;render();};
function setPracticeView(compact){document.body.classList.toggle('focus-mode',compact);$('focusMode').setAttribute('aria-pressed',String(compact));$('focusMode').textContent=compact?'Full view':'Compact view';try{localStorage.setItem('piano-compact-view',String(compact));}catch{}}
try{setPracticeView(localStorage.getItem('piano-compact-view')!=='false');}catch{setPracticeView(true);}
// Display preferences belong to this device, like the compact view, not to a piece.
function loadDisplay(){let saved={};try{saved=JSON.parse(localStorage.getItem('piano-display')||'{}')||{};}catch{}if(!saved.accidentalColours&&saved.purple===false)saved.accidentalColours='off';if(saved.dailyGoal===undefined)saved.dailyGoal=daily.goal;const d=Object.fromEntries(settings.filter(s=>s.scope==='device').map(s=>[s.key,validate(s.key,saved[s.key])]));d.keys=validKeys(saved.keys);return d;}
let display=loadDisplay();
function applyDisplay(){const root=document.documentElement;for(const [name,key] of [['--rh','rhColor'],['--lh','lhColor'],['--acc-key','accKeyColour'],['--acc-chromatic','accChromaticColour']])root.style.setProperty(name,display[key]);document.body.classList.toggle('one-colour',display.handColours==='one');document.body.classList.toggle('acc-chromatic-only',display.accidentalColours==='chromatic');document.body.classList.toggle('plain-accidentals',display.accidentalColours==='off');document.body.classList.toggle('paper-notation',display.paper);$('cueNowLabel').textContent=display.handColours==='one'?'Now · both hands in one colour':'Now · each hand in its own colour';$('handColourHelp').textContent=display.handColours==='one'?'Current notes in both hands use the right-hand colour (orange by default).':'Green = left hand; orange = right hand (by default).';if(display.theme==='auto')delete root.dataset.theme;else root.dataset.theme=display.theme;root.dataset.uiScale=display.uiScale;syncKeys();try{localStorage.setItem('piano-display',JSON.stringify(display));}catch{}}
// Settings: every control with data-setting, inline or in the dialog, is bound and refreshed here.
const settingValue=key=>settingByKey[key].scope==='device'?display[key]:state[key];
function syncSettings(){
 for(const el of document.querySelectorAll('[data-setting]')){const v=settingValue(el.dataset.setting);if(el.type==='checkbox')el.checked=v;else if(!(el.type==='number'&&document.activeElement===el))el.value=String(v);}
 for(const out of document.querySelectorAll('[data-output]'))out.textContent=settingValue(out.dataset.output)+(settingByKey[out.dataset.output].unit||'');
 for(const el of document.querySelectorAll('[data-setting="pageMeasures"]'))el.disabled=state.scoreView!=='around';
 for(const el of document.querySelectorAll('[data-setting="sectionSize"]'))el.disabled=activeId===BUILTIN;
 $('presetSelect').value=matchingPreset(settingValue,activeId===BUILTIN);
}
function setSectionSize(size){if(activeId===BUILTIN||size===state.sectionSize)return;stopAudio();stopMic();state.sectionSize=size;sections=makeSections(score.measures,size);for(const p of ['learn','mix','polish','perform'])state.stages[p].section=p==='perform'?sections.length-2:0;state.section=state.stages[state.phase].section;fillSelectors();render();}
function setLearnOrder(order){state.learnOrder=order;if(state.stages.learn.completed)return save();const hand=order==='right'?'right':'left';state.stages.learn.hand=hand;if(state.phase==='learn'){state.hand=hand;render();}else save();}
function changeSetting(key,raw){
 const s=settingByKey[key],value=validate(key,raw);
 if(s.scope==='device'){display[key]=value;applyDisplay();if(s.refresh==='estimate')renderEstimate();}
 else if(s.refresh==='sections')setSectionSize(value);
 else if(s.refresh==='learnOrder')setLearnOrder(value);
 else{state[key]=value;
  if(s.refresh==='render')render();
  else if(s.refresh==='dim'){$('notation').style.setProperty('--dim',state.contextDim/100);save();}
  else if(s.refresh==='marks'){save();$('cueGuide').hidden=!state.showCueGuide;followLine=null;markNotes(transport?sectionStart()+positionBeat:-1);}
  else save();}
 syncSettings();
}
// Presets and restored settings change several keys at once, then refresh everything once.
function applyValues(values){let size=null;for(const [key,raw] of Object.entries(values)){const s=settingByKey[key];if(!s)continue;const value=validate(key,raw);if(s.scope==='device')display[key]=value;else if(key==='sectionSize')size=value;else state[key]=value;}applyDisplay();if(size!==null&&size!==state.sectionSize&&activeId!==BUILTIN)setSectionSize(size);else render();renderEstimate();}
function bindSettingControls(root=document){for(const el of root.querySelectorAll('[data-setting]')){const key=el.dataset.setting,handler=()=>changeSetting(key,el.type==='checkbox'?el.checked:el.value);if(el.type==='range'||el.type==='color')el.oninput=handler;el.onchange=handler;}}
function settingControl(s){
 const row=document.createElement('label'),name=document.createElement('span'),scope=document.createElement('small');row.className='setting'+(s.type==='check'?' setting-check':'');name.textContent=s.label;scope.className='scope';scope.textContent=s.scope==='piece'?'this piece':'all pieces';scope.title=s.scope==='piece'?'Saved with this piece':'Saved for every piece on this device';
 let input;if(s.type==='select'){input=document.createElement('select');for(const [v,l] of s.options)input.append(new Option(l,String(v)));}else{input=document.createElement('input');input.type={check:'checkbox',color:'color',range:'range',number:'number'}[s.type];if(s.min!==undefined)Object.assign(input,{min:s.min,max:s.max,step:s.step});}
 input.dataset.setting=s.key;input.id='set-'+s.key;
 if(s.type==='range'){const out=document.createElement('output');out.dataset.output=s.key;name.append(' ',out);}
 if(s.type==='check')row.append(input,name,scope);else row.append(name,scope,input);
 if(s.help){const help=document.createElement('small');help.className='setting-help';help.textContent=s.help;row.append(help);}
 return row;
}
const keyName=code=>!code?'Not set':({Space:'Space',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',Comma:',',Period:'.',Slash:'/',Semicolon:';',Quote:"'",BracketLeft:'[',BracketRight:']',Backslash:'\\',Minus:'-',Equal:'=',Backquote:'`',Enter:'Enter'}[code]??code.replace(/^Key|^Digit|^Numpad/,''));
let capturingKey=null;
function syncKeys(){for(const b of document.querySelectorAll('[data-action]'))b.textContent=capturingKey===b.dataset.action?'Press a key…':keyName(display.keys[b.dataset.action]);$('shortcutHelp').textContent='Keys: '+actions.filter(([id])=>display.keys[id]).map(([id,label])=>keyName(display.keys[id])+' '+label.toLowerCase()).join(' · ')+'.';}
function buildSettingsDialog(){
 const tabs=$('settingsTabs'),panels=$('settingsPanels');
 const select=id=>{for(const [g] of groups){$('tab-'+g).setAttribute('aria-selected',String(g===id));$('tab-'+g).tabIndex=g===id?0:-1;$('panel-'+g).hidden=g!==id;}};
 for(const [id,label] of groups){
  const tab=document.createElement('button');Object.assign(tab,{type:'button',id:'tab-'+id,textContent:label});tab.setAttribute('role','tab');tab.setAttribute('aria-controls','panel-'+id);tab.onclick=()=>select(id);tab.onkeydown=e=>{if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft'].includes(e.key))return;e.preventDefault();const i=groups.findIndex(g=>g[0]===id),next=groups[(i+(e.key==='ArrowDown'||e.key==='ArrowRight'?1:groups.length-1))%groups.length][0];select(next);$('tab-'+next).focus();};tabs.append(tab);
  const panel=document.createElement('div');Object.assign(panel,{id:'panel-'+id,className:'settings-panel'});panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','tab-'+id);
  for(const s of settings.filter(s=>s.group===id))panel.append(settingControl(s));
  const button=(text,onclick)=>{const b=document.createElement('button');Object.assign(b,{type:'button',textContent:text,onclick});return b;};
  if(id==='display')panel.append(button('Reset colours',()=>applyValues(Object.fromEntries(['rhColor','lhColor','handColours','accidentalColours','accKeyColour','accChromaticColour'].map(k=>[k,settingByKey[k].default])))));
  if(id==='keys'){for(const [action,label] of actions){const row=document.createElement('div'),name=document.createElement('span'),b=button('',()=>{capturingKey=action;syncKeys();});row.className='setting key-row';name.textContent=label;b.dataset.action=action;row.append(name,b);panel.append(row);}
   const help=document.createElement('p');help.className='setting-help wide';help.textContent='Choose an action, then press the key to use. Escape cancels; a key used elsewhere moves to the new action. Keys never fire while you type in a field.';panel.append(help,button('Reset shortcuts',()=>{display.keys=validKeys({});applyDisplay();}));}
  if(id==='data'){const restore=document.createElement('label'),box=document.createElement('input');restore.className='setting setting-check wide';Object.assign(box,{type:'checkbox',id:'restoreDevice'});restore.append(box,' Also restore display and shortcut settings from a backup');
   const help=document.createElement('p');help.className='setting-help wide';help.textContent='Backups contain your imported scores, progress for every piece, daily practice totals and these settings. Display and shortcut settings are only restored when you tick the box, because they usually belong to one device.';
   panel.append(button('Download library backup',()=>$('exportProgress').click()),button('Restore a backup',()=>$('importProgress').click()),restore,help);}
  panels.append(panel);
 }
 select('score');bindSettingControls(panels);
}
function openSettings(){capturingKey=null;syncSettings();syncKeys();$('settingsStatus').textContent='';if(!$('settingsDialog').open)$('settingsDialog').showModal();}
// Key capture runs before every other key handler.
document.addEventListener('keydown',event=>{if(!capturingKey)return;event.preventDefault();event.stopImmediatePropagation();if(event.code!=='Escape'){for(const k of Object.keys(display.keys))if(display.keys[k]===event.code)display.keys[k]='';display.keys[capturingKey]=event.code;}capturingKey=null;applyDisplay();},true);
buildSettingsDialog();bindSettingControls($('soundState').closest('details'));bindSettingControls($('micOctaveTolerance').parentElement);
applyDisplay();
$('openSettings').onclick=$('moreSettings').onclick=openSettings;
$('presetSelect').onchange=()=>{const id=$('presetSelect').value;if(!presets[id])return;applyValues(presets[id].values);$('settingsStatus').textContent=presets[id].label+' preset applied. Change anything you like; the preset then shows Custom.';};
$('applyAll').onclick=()=>{const values=Object.fromEntries(settings.filter(s=>s.scope==='piece'&&s.group).map(s=>[s.key,state[s.key]]));try{localStorage.setItem('piano-piece-defaults',JSON.stringify(values));let count=1;for(const id of [BUILTIN,...library.map(e=>e.id)]){if(id===activeId)continue;const key=progressKey(id),saved=JSON.parse(localStorage.getItem(key)||'null');if(!saved)continue;Object.assign(saved,values);if(id===BUILTIN)saved.sectionSize=2;localStorage.setItem(key,JSON.stringify(saved));count++;}$('settingsStatus').textContent='Applied to '+count+' piece'+(count===1?'':'s')+' and to pieces you import later. Progress is unchanged.';}catch{$('settingsStatus').textContent='Could not save: browser storage is unavailable.';}};
$('focusMode').onclick=()=>{setPracticeView(!document.body.classList.contains('focus-mode'));render();};
$('toggleLibrary').onclick=()=>{const open=document.body.classList.toggle('library-open');$('toggleLibrary').setAttribute('aria-expanded',String(open));$('toggleLibrary').textContent=open?'Hide library':'Show library';};
for(const name of ['volume','leftVolume','rightVolume'])$(name).oninput=()=>{state[name]=Number($(name).value);$(name+'Label').textContent=state[name]+'%';if(name==='volume')piano?.volume(state.volume/100);};
for(const name of ['volume','leftVolume','rightVolume'])$(name).onchange=()=>{save();if(name!=='volume'&&playing)play(transport.practice,positionBeat,true);};
$('markedTempo').onclick=()=>{$('tempo').value=Math.max(30,Math.min(180,Math.round(score.tempo)));$('tempo').onchange();$('bpmLabel').textContent=state.tempo+' BPM';};
$('sectionNotes').oninput=()=>{const key=recordKey(state,state.section,state.hand),text=$('sectionNotes').value.slice(0,2000);if(text)state.notes[key]=text;else delete state.notes[key];save();};
// Listening presets only move the two hand sliders.
for(const [id,left,right] of [['hearLeft',80,0],['hearRight',0,80],['hearBoth',70,80]])$(id).onclick=()=>{state.leftVolume=left;state.rightVolume=right;for(const name of ['leftVolume','rightVolume']){$(name).value=state[name];$(name+'Label').textContent=state[name]+'%';}save();if(playing)play(transport.practice,positionBeat,true);};
$('printScore').onclick=()=>print();
// Reflow automatic measures-per-line after rotation or resizing, but never interrupt playback or a check.
let resizeTimer=0;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!transport&&!micStream&&!midiPractice&&(largeScore()?1:lineBars(state.barsPerLine,innerWidth))!==renderedLineBars)render();},250);});
$('seek').oninput=()=>{$('timeLabel').textContent=clockText(Number($('seek').value))+' / '+clockText(sectionLength());};
$('seek').onchange=()=>seekTo(Number($('seek').value));
$('importProgress').onchange=restoreBackup;
$('downloadAudio').onclick=async()=>{const button=$('downloadAudio');button.disabled=true;stopAudio();stopMic();try{const tempo=state.tempo,start=sectionStart(),end=starts[section().end],events=selectedEvents(),length=end-start,levels={left:voiceLevel('left'),right:voiceLevel('right'),melody:.65},volume=(state.volume??75)/100,filename=score.title.replace(/[^a-z0-9]+/gi,'-')+'-mm-'+section().start+'-'+section().end+'-'+state.hand+'-'+tempo+'bpm.wav';const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)throw new Error('Audio export is not available in this browser.');const offline=new Offline(2,Math.ceil((length*60/tempo+.7)*44100),44100),instrument=new PianoSound(offline);instrument.volume(volume);await instrument.load(events.flatMap(e=>e.notes),(done,all)=>{$('downloadStatus').textContent='Preparing piano samples '+done+'/'+all+'…';});$('downloadStatus').textContent='Rendering your piano audio…';for(const e of scheduleFrom(events,start,end))for(const n of e.notes)instrument.note(n,.03+e.at*60/tempo,e.length*60/tempo,levels[e.voice],e.voice==='left'?-.15:e.voice==='right'?.15:0);const audio=await offline.startRendering(),blob=encodeWav(audio),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('downloadStatus').textContent='Piano WAV ready: '+filename+'. No count-in or metronome. Credit Alexander Holm if redistributing this sampled audio.';}catch(error){$('downloadStatus').textContent='Could not export the audio. Check the connection and try again. '+error.message;}finally{button.disabled=false;}};
// Shortcut actions; the keys come from the device settings. Form controls keep their own keys.
const shortcuts={playPause:()=>{if(transport)pausePlayback();else play();},previousNote:()=>$('previousNote').click(),nextNote:()=>$('nextNote').click(),openSettings,peek:()=>$('notation').classList.add('peek'),loop:()=>{const s=$('loop');s.selectedIndex=(s.selectedIndex+1)%s.options.length;$('playStatus').textContent='Loop: '+s.selectedOptions[0].textContent;},metronome:()=>{$('metronome').checked=!$('metronome').checked;$('playStatus').textContent='Metronome '+($('metronome').checked?'on':'off')+(playing?' from the next start':'');},rate1:()=>rateKey(0),rate2:()=>rateKey(1),rate3:()=>rateKey(2),nextRound:()=>$('next').click()};
const rateKey=i=>document.querySelector('[data-rating="'+i+'"]').click();
const typing=event=>/^(INPUT|SELECT|TEXTAREA|BUTTON|SUMMARY|A)$/.test(event.target.tagName)||event.target.isContentEditable||event.ctrlKey||event.metaKey||event.altKey;
document.addEventListener('keyup',event=>{if(event.code===display.keys.peek)$('notation').classList.remove('peek');const i=virtualCodes.indexOf(event.code);if(i>=0)virtualKey(60+12*virtualOctave+i,false);});
document.addEventListener('keydown',event=>{if(tapCheck&&(event.code===display.keys.playPause||event.code==='Space')){event.preventDefault();if(!event.repeat)tapNow();return;}if(typing(event))return;if(midiConnection.input===midiConnection.virtual){const i=virtualCodes.indexOf(event.code);if(i>=0){event.preventDefault();if(!event.repeat){const n=60+12*virtualOctave+i;virtualKey(n,true);playReference(n);}return;}if(event.code==='KeyZ'||event.code==='KeyX'){virtualOctave=Math.max(-3,Math.min(2,virtualOctave+(event.code==='KeyX'?1:-1)));$('midiStatus').textContent='Computer keys now play C'+(4+virtualOctave)+' to C'+(5+virtualOctave)+'.';return;}}if($('settingsDialog').open)return;const action=actions.find(([id])=>display.keys[id]===event.code)?.[0];if(action){event.preventDefault();shortcuts[action]();}});

render();

$('restoreProgress').onclick=()=>$('importProgress').click();

for(const [id,direction] of [['previousNote',-1],['nextNote',1]])$(id).onclick=()=>{const at=stepBeat(cues,sectionStart()+positionBeat,direction);if(at!==undefined){stopAudio(false);seekTo(at-sectionStart());}};

const midiKeys=new MidiKeys();let midiAttacks=new Set();
function stopMidiPractice(){if(midiRhythm)$('midiResults').textContent='Timed check cancelled because playback stopped or changed. Start a new check for a complete result.';midiPractice=null;midiRhythm=null;if($('midiStop')){$('midiStop').hidden=true;$('midiStart').hidden=false;$('midiFeedback').textContent='Uses your selected section and hand(s). Checks notes and octaves, including chords. Rests and timing are self-checked.';}}
function clearMidi(){if(midiRhythm||midiPractice)stopAudio();stopMidiPractice();midiKeys.clear();midiAttacks.clear();$('midiHeard').textContent='None';document.querySelectorAll('#keyboard .midi-held').forEach(n=>n.classList.remove('midi-held'));$('midiStart').disabled=true;$('midiTimed').disabled=true;}
const midiConnection=new MidiConnection({onPorts:(ports,selected)=>{
 const select=$('midiInput');select.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Select your piano';select.append(placeholder);
 for(const port of ports){const o=document.createElement('option');o.value=port.id;o.textContent=port.name||port.manufacturer||'MIDI input';select.append(o);}select.value=selected||'';select.disabled=!ports.length;
 $('midiStatus').textContent=selected?'Connected. Play a key to check reception.':ports.length>1?'Choose your piano from MIDI input, or the on-screen keyboard.':midiConnection.access?'No MIDI piano found. Connect and turn on the piano; this list updates automatically. Or choose On-screen keyboard.':'This browser has no Web MIDI. Choose On-screen keyboard to use wait mode and the timed check with the keys below or your computer keyboard.';
},onLost:silent=>{clearMidi();for(const n of virtualHeld)midiKeys.read([128,n,0]);virtualHeld.clear();if(!silent)$('midiStatus').textContent='MIDI input disconnected or changed. Select a connected input to continue.';},onMessage:data=>{
 const message=midiKeys.read(data,$('midiChannel').value);if(!message)return;const held=midiKeys.notes();$('midiHeard').textContent=held.length?held.map(noteName).join(' + '):'None';document.querySelectorAll('#keyboard button').forEach(n=>n.classList.toggle('midi-held',held.includes(Number(n.dataset.note))));
 if(midiRhythm&&message.type==='on'&&transport&&!transport.paused){const absolute=(context.currentTime-transport.start)-transport.count*transport.seconds+(sectionStart()+transport.from)*transport.seconds;const result=midiRhythm.hit(message.note,absolute);$('midiFeedback').textContent=result.kind==='ignored'?'Wait for the count-in to finish.':result.kind==='extra'?'Unexpected '+noteName(message.note)+'. Keep the pulse going.':noteName(message.note)+': '+result.kind+(result.delta?' ('+Math.round(Math.abs(result.delta)*1000)+' ms)':'')+'. Keep going.';}
 if(!midiPractice)return;if(message.type==='on')midiAttacks.add(message.note);
 const target=midiPractice.targets[midiPractice.index];
 if(matchesTarget(target,held,midiAttacks)){
  midiPractice.index++;midiAttacks.clear();
  if(midiPractice.index===midiPractice.targets.length){const count=midiPractice.index;stopMidiPractice();markNotes(-1);$('midiFeedback').textContent='Completed '+count+' note entries. Pitches and octaves matched. Now practice the written rhythm and rests.';return;}
  showMidiTarget();
 }else{const extra=held.filter(n=>!target.notes.includes(n));$('midiFeedback').textContent=extra.length?'Release '+extra.map(noteName).join(' + ')+'. Target: '+target.notes.map(noteName).join(' + '):'Play / hold '+target.notes.map(noteName).join(' + ')+'. Replay each new or repeated note.';}
}});
for(let channel=0;channel<16;channel++){const o=document.createElement('option');o.value=channel;o.textContent=channel+1;$('midiChannel').append(o);}
$('midiConnect').onclick=async()=>{
 if(!navigator.requestMIDIAccess){await midiConnection.connect(null);$('midiDisconnect').hidden=false;$('midiConnect').hidden=true;return;}
 $('midiConnect').disabled=true;$('midiStatus').textContent='Waiting for MIDI permission…';
 try{await midiConnection.connect(options=>navigator.requestMIDIAccess(options));$('midiDisconnect').hidden=false;$('midiConnect').hidden=true;}catch(error){await midiConnection.connect(null);$('midiDisconnect').hidden=false;$('midiConnect').hidden=true;$('midiStatus').textContent=(error.name==='NotAllowedError'?'MIDI permission was blocked. Allow MIDI for this site, or open it directly in desktop Chrome or Edge.':'Could not open MIDI: '+error.message)+' The on-screen keyboard is still available as an input.';}finally{$('midiConnect').disabled=false;}
};
$('midiInput').onchange=async()=>{try{await midiConnection.select($('midiInput').value,true);$('midiStart').disabled=!midiConnection.input;$('midiTimed').disabled=!midiConnection.input;const virtual=midiConnection.input===midiConnection.virtual;$('midiStatus').textContent=virtual?'On-screen keyboard selected. Tap the keys under Note-by-note guide & keyboard, or use A W S E D F T G Y H U J K (C4 to C5); Z and X change octave.':midiConnection.input?'Connected to '+midiConnection.input.name+'. Play a key.':'Select a MIDI input.';if(virtual){$('practiceExtras').open=true;$('keyboard').closest('details').open=true;}}catch(error){clearMidi();$('midiStatus').textContent='Could not open that input. Close other MIDI apps and try again.';}};
$('midiChannel').onchange=()=>{clearMidi();$('midiStart').disabled=!midiConnection.input;$('midiTimed').disabled=!midiConnection.input;$('midiStatus').textContent='Channel changed. Release the keys before playing again.';};
$('midiDisconnect').onclick=()=>{midiConnection.disconnect();$('midiInput').replaceChildren();$('midiInput').disabled=true;$('midiDisconnect').hidden=true;$('midiConnect').hidden=false;$('midiStatus').textContent='MIDI disconnected.';};
function showMidiTarget(){const target=midiPractice.targets[midiPractice.index];updatePosition(target.beat-sectionStart());markNotes(target.beat);$('midiFeedback').textContent='Entry '+(midiPractice.index+1)+' of '+midiPractice.targets.length+': play / hold '+target.notes.map(noteName).join(' + ')+'.';$('playStatus').textContent='MIDI practice: waiting at measure '+barAt(target.beat)+'.';}
$('midiStart').onclick=()=>{if(!midiConnection.input)return;stopAudio();stopMic();midiKeys.clear();midiAttacks.clear();const targets=midiTargets(eventsFor(score,state.hand,section().start,section().end));if(!targets.length)return;midiPractice={targets,index:0};$('midiStart').hidden=true;$('midiStop').hidden=false;showMidiTarget();};

function finishMidiRhythm(){if(!midiRhythm)return;const r=midiRhythm.summary();recordAccuracy(midiRhythm);midiRhythm=null;$('midiResults').textContent='Completed: '+r.onTime+' / '+r.expected+' on time; '+r.early+' early, '+r.late+' late, '+r.missed+' missed, '+r.wrong+' wrong-pitch, '+r.extra+' extra attacks. Checks note starts and pitches, not hold lengths, pedal, or fingering.';$('midiStop').hidden=true;$('midiStart').hidden=false;}
$('midiTimed').onclick=async()=>{if(!midiConnection.input)return;const input=midiConnection.input;clearLoop();stopAudio();stopMic();midiKeys.clear();midiAttacks.clear();$('midiResults').textContent='';state.countBars=Math.max(1,state.countBars??1);syncSettings();await play(true,0);if(!playing||midiConnection.input!==input)return;midiRhythm=new RhythmCheck(eventsFor(score,state.hand,section().start,section().end),state.tempo,$('midiStrictness').value);$('midiStop').hidden=false;$('midiFeedback').textContent='Count in, then follow the score. Timing window: ±'+Math.round(midiRhythm.window*1000)+' ms. Keep going after slips.';};
$('midiStop').onclick=()=>{if(midiRhythm){finishMidiRhythm();$('midiResults').textContent='Stopped early. '+$('midiResults').textContent.replace('Completed: ','');}stopAudio();stopMidiPractice();markNotes(-1);$('playStatus').textContent='MIDI practice stopped.';};

function renderPlan(){
 renderLibraryList();renderHistory();
 const names={learn:'Separate hands',mix:'Hands together',polish:'Polishing'},ids={learn:'targetLearn',mix:'targetMix',polish:'targetPolish'};
 $('stagePlan').replaceChildren();let total=0,remaining=0;
 for(const phase of ['learn','mix','polish']){const target=state.targets[phase],done=state.stages[phase].completed;total+=target;remaining+=Math.max(0,target-done);const item=document.createElement('div'),title=document.createElement('strong'),label=document.createElement('span'),bar=document.createElement('progress');title.textContent=names[phase];label.textContent=done+' / '+target+' rounds'+(done>target?' · '+(done-target)+' extra':'');bar.max=target;bar.value=Math.min(done,target);bar.setAttribute('aria-label',names[phase]+' completed rounds');item.append(title,label,bar);$('stagePlan').append(item);$(ids[phase]).value=target;}
 $('planTotal').textContent=total+' planned rounds · '+remaining+' remaining'+(activeId===BUILTIN?'':' · '+state.sectionSize+'-measure sections');
 const left=Math.max(0,(state.targets[state.phase]||0)-state.completed);
 $('stageAdvice').textContent=state.phase==='perform'?'Play through the complete piece with playback, count-in, looping, MIDI, and note navigation. Your play-throughs are saved separately.':left?left+' rounds left in this stage’s plan. Move on when you can return to the passages cleanly at a comfortable tempo. All tabs remain available.':'You have reached this stage’s target. Move to the next tab when ready, or keep going for extra rounds.';
 $('roundLabel').textContent=roundText();
}
$('saveTargets').onclick=()=>{const values=['targetLearn','targetMix','targetPolish'].map(id=>Number($(id).value));if(values.some(n=>!Number.isInteger(n)||n<1||n>10000)){$('targetStatus').textContent='Enter whole numbers between 1 and 10,000.';return;}['learn','mix','polish'].forEach((p,i)=>state.targets[p]=values[i]);save();renderPlan();$('targetStatus').textContent='Targets saved. Extra rounds are always available.';};
function downloadJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function refreshLibrary(){const select=$('scoreLibrary');select.replaceChildren(new Option(builtinScore.title,BUILTIN));for(const entry of library)select.append(new Option(entry.score.title,entry.id));select.value=activeId;renderLibraryList();}
function activateScore(id){const entry=library.find(e=>e.id===id);if(id!==BUILTIN&&!entry)return;stopAudio();stopMic();save();activeId=id;score=id===BUILTIN?builtinScore:entry.score;starts=measureStarts(score);sections=id===BUILTIN?builtinSections:makeSections(score.measures);storageKey=progressKey(id);loadState();fillSelectors();render();refreshLibrary();try{localStorage.setItem('piano-active-score',id);}catch{}$('midiResults').textContent='';}
$('scoreLibrary').onchange=()=>activateScore($('scoreLibrary').value);
$('addScores').onclick=()=>$('scoreFiles').click();
$('scoreFiles').onchange=async event=>{const files=[...event.target.files];if(!files.length)return;$('addScores').disabled=true;$('scoreLibrary').disabled=true;const results=[];let last=null;
 try{for(const file of files){try{const source=await readMusicXMLFile(file);let parsed,partId=null;try{parsed=parseMusicXML(source,file.name);}catch(error){if(!error.parts)throw error;partId=await choosePianoPart(error.parts,file.name);if(!partId){results.push(file.name+': import cancelled.');continue;}parsed=parseMusicXML(source,file.name,DOMParser,partId);}const id=await scoreId(partId?source+'\nPiano part: '+partId:source);if(library.some(e=>e.id===id)){results.push(file.name+': already in your library; progress kept.');last=id;continue;}const entry={id,source,filename:file.name,partId,score:parsed};await storeScore(entry);library.push(entry);last=id;results.push(file.name+': imported '+parsed.measures+' measures.');}catch(error){results.push(file.name+': '+error.message);}}if(last)activateScore(last);$('libraryStatus').textContent=results.join('\n');}finally{$('addScores').disabled=false;$('scoreLibrary').disabled=false;event.target.value='';}
};
async function restoreBackup(event){const file=event.target.files?.[0];if(!file)return;try{
 if(file.size>50000000)throw new Error('This backup exceeds 50 MB.');const data=JSON.parse(await file.text());
 if(data.version===2){if(!Array.isArray(data.entries)||data.entries.length>100||!data.progress||typeof data.progress!=='object')throw new Error('Invalid library backup.');const validated=[];
   for(const entry of data.entries){if(typeof entry.source!=='string'||typeof entry.filename!=='string')throw new Error('Invalid score entry.');const id=await scoreId(entry.partId?entry.source+'\nPiano part: '+entry.partId:entry.source);if(id!==entry.id)throw new Error('A score in this backup does not match its identity.');validated.push({...entry,id,score:parseMusicXML(entry.source,entry.filename,DOMParser,entry.partId||null)});}
   // Validate every state before writing anything.
   const states=[];for(const [id,incoming] of Object.entries(data.progress)){const entry=validated.find(e=>e.id===id)||library.find(e=>e.id===id);if(id!==BUILTIN&&!entry)throw new Error('Backup refers to an unknown score.');const piece=id===BUILTIN?builtinScore:entry.score;const parts=id===BUILTIN?builtinSections:makeSections(piece.measures,[1,2,4].includes(incoming?.sectionSize)?incoming.sectionSize:2);states.push([id,checkedState(incoming,parts,piece.measures)]);}
   for(const entry of validated){await storeScore(entry);if(!library.some(e=>e.id===entry.id))library.push(entry);}
   for(const [id,incoming] of states){const key=progressKey(id);let existing={};try{existing=JSON.parse(localStorage.getItem(key)||'{}');}catch{}for(const [k,r] of Object.entries(existing.records||{}))if(r.last>(incoming.records[k]?.last||0))incoming.records[k]=r;for(const p of ['learn','mix','polish','perform'])if((existing.stages?.[p]?.completed||0)>incoming.stages[p].completed)incoming.stages[p]=existing.stages[p];incoming.notes={...(existing.notes||{}),...incoming.notes};if((existing.practiceTiming?.activeSeconds||0)>(incoming.practiceTiming?.activeSeconds||0))incoming.practiceTiming=timingState(existing.practiceTiming);localStorage.setItem(key,JSON.stringify(incoming));}
   if(data.daily){daily=mergeDaily(daily,data.daily);saveDaily();}
   if(data.settings?.device&&typeof data.settings.device==='object'&&$('restoreDevice').checked){const incoming=data.settings.device;for(const s of settings.filter(s=>s.scope==='device'))display[s.key]=validate(s.key,incoming[s.key],display[s.key]);display.keys=validKeys({...display.keys,...incoming.keys});applyDisplay();}
   // Reload without saving the stale in-memory state over the restored one.
   loadState();activateScore(data.activeId===BUILTIN||library.some(e=>e.id===data.activeId)?data.activeId:activeId);
 }else{if(activeId!==BUILTIN)throw new Error('Select Black Is the Color before restoring its legacy backup.');const incoming=validateProgress(data);for(const [key,value] of Object.entries(incoming)){const existing=state.records[key];if(!existing||value.last>(existing.last||0))state.records[key]=value;}save();render();}
 $('importStatus').textContent='Backup restored. More recent practice records and higher completed-round counts were kept.';
 }catch(error){$('importStatus').textContent='Restore failed: '+error.message;}finally{event.target.value='';}}
function checkedState(value,parts,measures){
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid saved progress.');
 const records={};for(const [key,r] of Object.entries(value.records||{})){const size=key.includes('/')?Number(key.split('/')[0]):2,index=Number(key.replace(/^\d\//,'').split(':')[0]);if(!recordKeyPattern.test(key)||index>=(size===2?parts.length:makeSections(measures,size).length)||!r||!Number.isInteger(r.attempts)||r.attempts<0||!Number.isInteger(r.clean)||r.clean<0||r.clean>r.attempts)throw new Error('Invalid practice record in backup.');records[key]={attempts:r.attempts,clean:r.clean,last:Number(r.last)||0,tempo:Number(r.tempo)||50,rating:[0,1,2].includes(r.rating)?r.rating:0};}
 const clean={records};for(const key of ['phase','hand','section','stages','targets','customStart','customEnd','practiceTiming','notes','flags','history','measureStats',...settings.filter(s=>s.scope==='piece').map(s=>s.key)])if(Object.hasOwn(value,key))clean[key]=value[key];
 const result=freshState(clean,parts,measures);result.practiceTiming=timingState(clean.practiceTiming);return result;
}
async function initializeLibrary(){try{library=(await listScores()).map(entry=>{try{return {...entry,score:parseMusicXML(entry.source,entry.filename,DOMParser,entry.partId||null)};}catch{return entry;}});refreshLibrary();const id=localStorage.getItem('piano-active-score');if(id&&id!==BUILTIN)activateScore(id);}catch{$('libraryStatus').textContent='Browser storage is unavailable. The built-in piece still works; imported scores require browser storage.';}}
initializeLibrary();


function renderLibraryList(){
 const list=$('libraryList');list.replaceChildren();
 for(const entry of [{id:BUILTIN,score:builtinScore},...library]){
  let saved={};try{saved=JSON.parse(localStorage.getItem(progressKey(entry.id))||'{}');}catch{}
  const phase=entry.id===activeId?state.phase:saved.phase,button=document.createElement('button'),title=document.createElement('strong'),detail=document.createElement('span');
  button.type='button';button.className='library-piece';button.setAttribute('aria-pressed',String(entry.id===activeId));title.textContent=entry.score.title;detail.textContent=entry.score.measures+' measures · '+({learn:'Separate hands',mix:'Hands together',polish:'Polishing',perform:'Whole piece'}[phase]||'Ready to start');button.append(title,detail);button.onclick=()=>activateScore(entry.id);list.append(button);
 }
}

$('downloadScore').onclick=()=>{const entry=library.find(e=>e.id===activeId);if(!entry)return;const url=URL.createObjectURL(new Blob([entry.source],{type:'application/vnd.recordare.musicxml+xml'})),a=document.createElement('a');a.href=url;a.download=score.title.replace(/[^a-z0-9]+/gi,'-')+'.musicxml';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

function renderEstimate(){
 const timing=state.practiceTiming||(state.practiceTiming=timingState()),estimate=estimatePractice(state);
 $('practiceEstimate').textContent=!estimate.remaining?'Practice plan completed':estimate.ready?'Estimated practice left: '+timeText(estimate.seconds):'Learning your pace';
 $('estimateDetail').textContent=!estimate.remaining?'Keep checking clean returns; completing a plan is not proof of mastery.':estimate.ready?'Range '+timeText(estimate.low)+' to '+timeText(estimate.high)+' · based on timed rounds and self-ratings.':'Time '+Math.max(0,3-timing.samples.length)+' more rated '+(3-timing.samples.length===1?'round':'rounds')+' (10+ seconds each).';
 $('practiceTimer').textContent=(timing.running?'Pause timer':'Start timer')+' · '+timeText(timing.activeSeconds);
 $('practiceTimer').setAttribute('aria-pressed',String(timing.running));
 const minutes=Math.floor((daily.days[today()]||0)/60);$('dailyTotal').textContent='Today '+minutes+(display.dailyGoal?' of '+display.dailyGoal+' min'+(minutes>=display.dailyGoal?' · goal reached':''):' min');
}
$('practiceTimer').onclick=()=>{state.practiceTiming.running=!state.practiceTiming.running;renderEstimate();save();};
let timerLast=Date.now(),timerSave=0;
setInterval(()=>{const now=Date.now(),elapsed=Math.min(2,(now-timerLast)/1000);timerLast=now;const t=state.practiceTiming||(state.practiceTiming=timingState());if(t.running&&!document.hidden){t.activeSeconds+=elapsed;addPractice(daily,today(),elapsed);if(!state.rated)t.roundSeconds+=elapsed;timerSave+=elapsed;if(timerSave>=5){save();saveDaily();timerSave=0;}}renderEstimate();},1000);
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();stopMic();state.practiceTiming.running=false;save();}timerLast=Date.now();renderEstimate();});
window.addEventListener('pagehide',()=>{stopAudio();stopMic();midiConnection.disconnect();state.practiceTiming.running=false;save();});
renderEstimate();

function choosePianoPart(parts,filename){
 return new Promise(resolve=>{const dialog=$('pianoPartDialog'),select=$('pianoPart');select.replaceChildren();for(const part of parts)select.append(new Option(part.name+' ('+part.id+')',part.id));$('pianoPartFile').textContent=filename;dialog.returnValue='cancel';dialog.onclose=()=>resolve(dialog.returnValue==='import'?select.value:null);dialog.showModal();});
}
$('removeScore').onclick=async()=>{const entry=library.find(e=>e.id===activeId);if(!entry)return;if(!confirm('Remove '+entry.score.title+' and its practice progress from this browser? Download a backup first if you want to keep it.'))return;try{await deleteScore(entry.id);activateScore(BUILTIN);library=library.filter(e=>e.id!==entry.id);localStorage.removeItem(progressKey(entry.id));refreshLibrary();$('libraryStatus').textContent=entry.score.title+' removed.';}catch(error){$('libraryStatus').textContent='Removal failed: '+error.message;}};
