// Recorded Yamaha C5 samples: Alexander Holm, Salamander, CC BY 3.0.
export const sampleNames = ['Ds1','Fs1','A1','C2','Ds2','Fs2','A2','C3','Ds3','Fs3','A3','C4','Ds4','Fs4','A4','C5','Ds5','Fs5'];
const pitchClass={C:0,Ds:3,Fs:6,A:9};
export const sampleMidi=name=>12*(Number(name.at(-1))+1)+pitchClass[name.slice(0,-1)];
export function sampleFor(note){return sampleNames.reduce((best,name)=>Math.abs(sampleMidi(name)-note)<Math.abs(sampleMidi(best)-note)?name:best,sampleNames[0]);}
export class PianoSound {
 constructor(context){this.context=context;this.buffers=new Map();this.pending=new Map();this.active=new Set();this.master=context.createGain();this.master.gain.value=.7;this.compressor=context.createDynamicsCompressor();this.compressor.threshold.value=-15;this.compressor.knee.value=15;this.compressor.ratio.value=3;this.master.connect(this.compressor);this.compressor.connect(context.destination);}
 volume(value){this.master.gain.setTargetAtTime(value,this.context.currentTime,.025);}
 async load(notes,onProgress=()=>{}){const names=[...new Set(notes.map(sampleFor))];let complete=0;onProgress(0,names.length);await Promise.all(names.map(async name=>{if(!this.buffers.has(name)){if(!this.pending.has(name)){const promise=(async()=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(new URL('assets/piano/'+name+'.mp3',import.meta.url),{signal:controller.signal});if(!response.ok)throw new Error('Sample unavailable');const buffer=await this.context.decodeAudioData(await response.arrayBuffer());this.buffers.set(name,buffer);}finally{clearTimeout(timeout);this.pending.delete(name);}})();this.pending.set(name,promise);}await this.pending.get(name);}onProgress(++complete,names.length);}));}
 note(note,when,duration,velocity=.7,pan=0){if(velocity<=0)return;const name=sampleFor(note),buffer=this.buffers.get(name);if(!buffer)throw new Error('Piano sample has not loaded');const ctx=this.context,source=ctx.createBufferSource(),gain=ctx.createGain(),panner=ctx.createStereoPanner();source.buffer=buffer;source.playbackRate.value=2**((note-sampleMidi(name))/12);gain.gain.setValueAtTime(Math.max(.001,velocity),when);gain.gain.setValueAtTime(Math.max(.001,velocity),when+duration);gain.gain.exponentialRampToValueAtTime(.0001,when+duration+.22);panner.pan.value=pan;source.connect(gain);gain.connect(panner);panner.connect(this.master);source.start(when);source.stop(when+duration+.25);const item={source,gain};this.active.add(item);source.onended=()=>{source.disconnect();gain.disconnect();panner.disconnect();this.active.delete(item);};}
 click(when,strong){const ctx=this.context,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=strong?1300:950;g.gain.setValueAtTime(.14,when);g.gain.exponentialRampToValueAtTime(.0001,when+.04);o.connect(g);g.connect(this.master);o.start(when);o.stop(when+.05);const item={source:o,gain:g};this.active.add(item);o.onended=()=>{o.disconnect();g.disconnect();this.active.delete(item);};}
 stop(){const now=this.context.currentTime;for(const {source,gain} of this.active){try{gain.gain.cancelScheduledValues(now);gain.gain.setValueAtTime(.0001,now);source.stop(now+.015);}catch{}}this.active.clear();}
}
export function mergeTies(events){const result=[];for(const event of events){if(event.tieEnd){const previous=result.findLast(p=>p.voice===event.voice&&p.tieStart&&Math.abs(p.beat+p.duration-event.beat)<.001&&p.notes.join(',')===event.notes.join(','));if(previous){previous.duration+=event.duration;previous.tieStart=event.tieStart;continue;}}result.push({...event});}return result;}
export function scheduleFrom(events,offset,end){return mergeTies(events).filter(e=>e.notes.length&&e.beat<end&&e.beat+e.duration>offset).map(e=>({...e,at:Math.max(e.beat,offset)-offset,length:Math.min(e.beat+e.duration,end)-Math.max(e.beat,offset)}));}
export function encodeWav(buffer){const channels=buffer.numberOfChannels,frames=buffer.length,bytes=frames*channels*2,result=new ArrayBuffer(44+bytes),view=new DataView(result);const str=(pos,text)=>[...text].forEach((c,i)=>view.setUint8(pos+i,c.charCodeAt(0)));str(0,'RIFF');view.setUint32(4,36+bytes,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,bytes,true);const arrays=Array.from({length:channels},(_,c)=>buffer.getChannelData(c));let p=44;for(let i=0;i<frames;i++)for(const a of arrays){const v=Math.max(-1,Math.min(1,a[i]));view.setInt16(p,v<0?v*32768:v*32767,true);p+=2;}return new Blob([result],{type:'audio/wav'});}
