import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DOMParser} from 'linkedom';
import {parseMusicXML,importedExcerpt} from '../import-score.js';import {eventsFor} from '../engine.js';import {scheduleFrom} from '../piano.js';import {midiTargets,RhythmCheck} from '../midi.js';import {makeCues} from '../follower.js';
const xml=fs.readFileSync(new URL('./fixtures/three-beat-study.musicxml',import.meta.url),'utf8');const parse=s=>parseMusicXML(s,'test.musicxml',DOMParser);
test('MusicXML preserves meter, fingerings, voices, accidental and clefs',()=>{const s=parse(xml);assert.equal(s.measures,2);assert.equal(s.beatsPerMeasure,3);assert.equal(s.clefs.right,'treble');assert.deepEqual(s.voices[0].events[0].notes,[60,64]);assert.deepEqual(s.voices[0].events[0].fingers,['1','3']);assert.deepEqual(s.voices[0].events[1].notes,[60,66]);assert.equal(eventsFor(s,'left',2,2)[0].beat,3);const abc=importedExcerpt(s,'both',1,2);assert.match(abc,/!1!!3!/);assert.match(abc,/\^F/);assert.match(abc,/M:3\/4/);});
test('overlapping voices sustain without false MIDI or playback attacks',()=>{const s=parse(xml),events=eventsFor(s,'both',1,2),audio=scheduleFrom(events,0,6);const c=audio.filter(e=>e.notes.includes(60));assert.equal(c.length,1);assert.equal(c[0].length,3);const targets=midiTargets(events);assert.deepEqual(targets[1].attacks,[66]);assert.ok(targets[1].notes.includes(60));assert.equal(new RhythmCheck(events,60).expected.length,6);assert.equal(makeCues(events,'both',1,3).find(e=>e.beat===3).selector,'.abcjs-v0.abcjs-mm1.abcjs-n0');});
test('reject unsupported notation before saving a misleading score',()=>{assert.throws(()=>parse(xml.replace('<staves>2</staves>','<transpose><chromatic>2</chromatic></transpose>')));assert.throws(()=>parse(xml.replace('<measure number="2">','<measure number="2"><barline><repeat direction="backward"/></barline>')),/Expand repeats/);assert.throws(()=>parse(xml.replace('<measure number="2">','<measure number="2"><attributes><time><beats>4</beats><beat-type>4</beat-type></time></attributes>')),/Changing time/);assert.throws(()=>parse('<html>no score</html>'));});
test('single-staff scores include a silent left staff',()=>{const s=parse(xml.replaceAll('<staff>2</staff>','<staff>1</staff>'));assert.ok(s.voices[1].events.every(e=>e.notes.length===0));});
test('eighth-note meter keeps quarter-note timing and measure boundaries',()=>{const s=parse(xml.replace('<divisions>4</divisions>','<divisions>8</divisions>').replace('<beat-type>4</beat-type>','<beat-type>8</beat-type>'));assert.equal(s.beatsPerMeasure,1.5);assert.equal(eventsFor(s,'right',2,2)[0].beat,1.5);assert.equal(scheduleFrom(eventsFor(s,'both',1,2),0,3).at(-1).length,1.5);});
test('starting at a tied continuation asks for a fresh MIDI attack',()=>{const s=parse(xml);s.voices[0].events.at(-1).tieEnds=[67];const events=eventsFor(s,'right',2,2);assert.deepEqual(midiTargets(events)[0].attacks,[67]);});
